const STORAGE_KEY = "paheliBazaarProgressV01";
const appState = { screen: "gate", data: { shops: [], puzzles: [], rounds: [], titles: [], reactions: {} }, progress: null, selectedShopId: null, selectedRoundId: null, selectedDifficulty: null, activePuzzle: null, activeRoundQueue: [], activeRoundIndex: 0, roundStats: null, mode: "shop", hintsUsed: 0, result: null, revealed: false };
async function loadJson(path){ const response = await fetch(path); if(!response.ok) throw new Error(`Could not load ${path}`); return response.json(); }
async function loadAppData(){ const [shops,puzzles,rounds,titles,reactions] = await Promise.all([loadJson('./data/shops.json'),loadJson('./data/puzzles.json'),loadJson('./data/rounds.json'),loadJson('./data/titles.json'),loadJson('./data/reactions.json')]); appState.data = {shops,puzzles,rounds,titles,reactions}; }
function getDefaultProgress(){ return { coins:0, solvedPuzzleIds:[], attemptedPuzzleIds:[], recentlyPlayedPuzzleIds:[], dailyChallengeHistory:[], shopStats:{}, earnedTitles:[], wrongAnswerSubmissions:[], dailyStreak:0, bestDailyStreak:0, lastDailyDate:null, totalCorrect:0, totalAttempts:0, skippedPuzzleIds:[], roundsCompleted:0, roundHistory:[], preferences:{ kidMode:false } }; }
function loadProgress(){ try{ const base=getDefaultProgress(); const saved=localStorage.getItem(STORAGE_KEY); if(!saved) return base; const parsed=JSON.parse(saved); return {...base, ...parsed, preferences:{...base.preferences, ...(parsed.preferences || {})}, shopStats:parsed.shopStats || {}, roundHistory:parsed.roundHistory || [], skippedPuzzleIds:parsed.skippedPuzzleIds || []}; }catch{ return getDefaultProgress(); } }
function saveProgress(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(appState.progress)); }
function resetProgress(){ if(confirm('Reset all Paheli Bazaar progress on this device?')){ appState.progress=getDefaultProgress(); saveProgress(); setScreen('progress'); } }
function addUnique(list,value){ if(!list.includes(value)) list.push(value); }
function randomFrom(list){ return list[Math.floor(Math.random()*list.length)]; }
function shuffle(list){ return [...list].sort(()=>Math.random()-0.5); }
function todayString(){ return new Date().toISOString().slice(0,10); }
function escapeHtml(value){ return String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
function normalizeAnswer(value){ return String(value || '').toLowerCase().trim().replace(/[.,!?;:'"“”‘’°₹]/g,'').replace(/\b(a|an|the)\b/g,'').replace(/\s+/g,' ').trim(); }
function checkExactAnswer(userInput,puzzle){ const input=normalizeAnswer(userInput); return puzzle.acceptableAnswers.map(normalizeAnswer).includes(input); }
function checkFlexibleAnswer(userInput,puzzle){ const input=normalizeAnswer(userInput); if(input.length < 2) return false; return puzzle.acceptableAnswers.some(answer=>{ const expected=normalizeAnswer(answer); return input===expected || (input.length>=4 && expected.includes(input)) || (expected.length>=4 && input.includes(expected)); }); }
function checkCreativeAnswer(userInput){ return String(userInput||'').trim().length >= 3; }
function checkAnswer(userInput,puzzle){ if(puzzle.inputType==='creative') return checkCreativeAnswer(userInput); if(puzzle.inputType==='flexible_text') return checkFlexibleAnswer(userInput,puzzle); return checkExactAnswer(userInput,puzzle); }
function calculateCoins({correct,hintsUsed,inputType}){ if(!correct) return 0; if(inputType==='creative') return 5; if(hintsUsed===0) return 10; if(hintsUsed===1) return 6; return 3; }
function ensureShopStats(shopId){ if(!appState.progress.shopStats[shopId]) appState.progress.shopStats[shopId]={attempted:0, solved:0, coins:0, hintsUsed:0}; return appState.progress.shopStats[shopId]; }
function getShopSolved(shopId){ return appState.progress.shopStats[shopId]?.solved || 0; }
function getShopAttempted(shopId){ return appState.progress.shopStats[shopId]?.attempted || 0; }
function isKidMode(){ return !!appState.progress?.preferences?.kidMode; }
function applyKidModeFilter(puzzles){ if(!isKidMode()) return puzzles; const filtered=puzzles.filter(p=>p.difficulty!=='tricky'); return filtered.length ? filtered : puzzles; }
function toggleKidMode(){ if(!appState.progress.preferences) appState.progress.preferences={kidMode:false}; appState.progress.preferences.kidMode=!appState.progress.preferences.kidMode; saveProgress(); setScreen('progress'); }
function rememberRecentPuzzle(puzzleId){ const recent=appState.progress.recentlyPlayedPuzzleIds || []; appState.progress.recentlyPlayedPuzzleIds=[puzzleId, ...recent.filter(id=>id!==puzzleId)].slice(0,20); }
function selectPuzzle({shopId=null,difficulty=null,excludeRecent=true,excludeIds=[]}={}){ let base=[...appState.data.puzzles]; if(shopId) base=base.filter(p=>p.shop===shopId); let candidates=[...base]; if(difficulty) candidates=candidates.filter(p=>p.difficulty===difficulty); if(!candidates.length && difficulty && shopId) candidates=[...base]; candidates=applyKidModeFilter(candidates); if(excludeIds.length){ const withoutExcluded=candidates.filter(p=>!excludeIds.includes(p.id)); if(withoutExcluded.length) candidates=withoutExcluded; } if(excludeRecent){ const nonRecent=candidates.filter(p=>!appState.progress.recentlyPlayedPuzzleIds.includes(p.id)); if(nonRecent.length>0) candidates=nonRecent; } const unseen=candidates.filter(p=>!appState.progress.attemptedPuzzleIds.includes(p.id)); const pool=unseen.length>0 ? unseen : candidates; return pool.length ? randomFrom(pool) : null; }
function getReaction(shopId,correct){ const shopReactions=appState.data.reactions[shopId]; if(!shopReactions) return correct ? 'Correct!' : 'Not quite.'; return randomFrom(shopReactions[correct?'correct':'wrong'] || []); }
function addTitle(titleId){ addUnique(appState.progress.earnedTitles,titleId); }
function unlockTitles(){ const solvedCount=appState.progress.solvedPuzzleIds.length; if(solvedCount>=5) addTitle('chotu_solver'); if(solvedCount>=15) addTitle('paheli_intern'); if(solvedCount>=30) addTitle('bazaar_thinker'); if(solvedCount>=100) addTitle('bazaar_ustad'); if(getShopSolved('logic_laddoo')>=10) addTitle('logic_laddoo_taster'); if(getShopSolved('emoji_puzzle')>=10) addTitle('emoji_detective'); if(getShopSolved('word_jumble_paan')>=10) addTitle('word_paan_champion'); if(getShopSolved('science_magic')>=10) addTitle('science_jadugar_junior'); if(getShopSolved('wrong_answer')>=10) addTitle('wrong_answer_maharaj'); if(appState.progress.dailyChallengeHistory.filter(item=>item.solved).length>=5) addTitle('daily_bazaar_regular'); }
function updateProgressAfterAnswer({puzzle,correct,coinsEarned,userInput}){ const progress=appState.progress; progress.totalAttempts += 1; progress.coins += coinsEarned; addUnique(progress.attemptedPuzzleIds,puzzle.id); rememberRecentPuzzle(puzzle.id); const shopStats=ensureShopStats(puzzle.shop); shopStats.attempted += 1; shopStats.coins += coinsEarned; shopStats.hintsUsed += appState.hintsUsed; if(correct && !progress.solvedPuzzleIds.includes(puzzle.id)){ addUnique(progress.solvedPuzzleIds,puzzle.id); progress.totalCorrect += 1; shopStats.solved += 1; } else if(correct){ progress.totalCorrect += 1; }
 if(puzzle.inputType==='creative' && correct){ progress.wrongAnswerSubmissions.push({puzzleId:puzzle.id, answer:userInput, date:todayString()}); }
 unlockTitles(); saveProgress(); }
function getDailyPuzzle(){ const date=todayString(); const eligible=applyKidModeFilter(appState.data.puzzles.filter(p=>p.inputType!=='creative')); const seed=[...date].reduce((sum,char)=>sum+char.charCodeAt(0),0); return eligible[seed % eligible.length]; }
function hasCompletedDaily(){ const date=todayString(); return appState.progress.dailyChallengeHistory.some(item=>item.date===date); }
function updateDailyStreak(date){ const p=appState.progress; if(!p.lastDailyDate){ p.dailyStreak=1; } else { const last=new Date(p.lastDailyDate); const current=new Date(date); const diffDays=Math.round((current-last)/(1000*60*60*24)); if(diffDays===1) p.dailyStreak += 1; else if(diffDays>1) p.dailyStreak = 1; }
 p.lastDailyDate=date; p.bestDailyStreak=Math.max(p.bestDailyStreak,p.dailyStreak); }
function completeDailyChallenge(puzzleId,correct){ if(hasCompletedDaily()) return; const date=todayString(); appState.progress.dailyChallengeHistory.push({date,puzzleId,solved:correct}); if(correct){ appState.progress.coins += 25; updateDailyStreak(date); }
 unlockTitles(); saveProgress(); }
function buildRoundQueue(roundId){ const round=appState.data.rounds.find(item=>item.id===roundId); if(!round) return []; let selected=[]; const pickFromCandidates=(candidates)=>{ candidates=applyKidModeFilter(candidates); if(!candidates.length) return null; const nonRecent=candidates.filter(p=>!appState.progress.recentlyPlayedPuzzleIds.includes(p.id)); if(nonRecent.length) candidates=nonRecent; const unseen=candidates.filter(p=>!appState.progress.attemptedPuzzleIds.includes(p.id)); const pool=unseen.length ? unseen : candidates; return pool.length ? randomFrom(pool) : null; }; if(round.mixingRule==='minimum_three_shops'){ const shops=shuffle(round.allowedShops).slice(0, Math.min(3,round.allowedShops.length)); shops.forEach(shopId=>{ const candidates=appState.data.puzzles.filter(p=>p.shop===shopId && round.difficulty.includes(p.difficulty) && !selected.some(x=>x.id===p.id)); const picked=pickFromCandidates(candidates); if(picked) selected.push(picked); }); } let candidates=appState.data.puzzles.filter(p=>round.allowedShops.includes(p.shop) && round.difficulty.includes(p.difficulty) && !selected.some(x=>x.id===p.id)); candidates=applyKidModeFilter(candidates); const nonRecent=candidates.filter(p=>!appState.progress.recentlyPlayedPuzzleIds.includes(p.id)); if(nonRecent.length >= round.puzzleCount-selected.length) candidates=nonRecent; const unseen=candidates.filter(p=>!appState.progress.attemptedPuzzleIds.includes(p.id)); const pool=unseen.length >= round.puzzleCount-selected.length ? unseen : candidates; selected=[...selected, ...shuffle(pool).slice(0, round.puzzleCount-selected.length)]; return selected.slice(0,round.puzzleCount); }
function setScreen(screenName){ appState.screen=screenName; renderApp(); window.scrollTo({top:0,behavior:'smooth'}); }
function renderHeader(){ const kidPill=isKidMode()?'<span class="pill kid-pill">🧒 Kid Mode</span>':''; return `<header class="header"><button class="brand" data-action="enter-bazaar"><span class="brand-mark">🧩</span><span>Paheli Bazaar</span></button><div class="pill-row"><span class="pill">🪙 ${appState.progress.coins}</span><span class="pill">✅ ${appState.progress.solvedPuzzleIds.length}/${appState.data.puzzles.length}</span>${kidPill}</div></header>`; }
function renderBottomNav(active){ return `<nav class="bottom-nav"><button class="nav-item ${active==='bazaar'?'active':''}" data-action="enter-bazaar">Bazaar</button><button class="nav-item ${active==='daily'?'active':''}" data-action="open-daily">Daily</button><button class="nav-item ${active==='rounds'?'active':''}" data-action="open-rounds">Rounds</button><button class="nav-item ${active==='progress'?'active':''}" data-action="open-progress">Progress</button></nav>`; }
function renderGate(){ return `<main class="gate-screen"><section class="card hero-card"><div class="logo-mark">🧩</div><p class="eyebrow">A puzzle mela for curious minds</p><h1>Paheli Bazaar</h1><p>Choose a shop. Solve a challenge. Earn coins. Become Bazaar Ustad.</p><button class="button button-primary" data-action="enter-bazaar">Enter Bazaar</button><div class="quick-actions"><button class="button button-secondary" data-action="open-daily">Daily Challenge</button><button class="button button-secondary" data-action="start-round" data-round-id="family_round">Family Round</button></div><p class="footer-note">140 curated puzzles · offline-ready · no login</p></section></main>`; }

function getFavoriteShopId(){ const entries=Object.entries(appState.progress.shopStats || {}); if(!entries.length) return null; entries.sort((a,b)=>(b[1].attempted||0)-(a[1].attempted||0)); return entries[0][0]; }
function getRecommendedAction(){ if(!hasCompletedDaily()) return {label:'Start Daily Challenge', action:'start-daily', note:'Daily puzzle is still open today.'}; const solved=appState.progress.solvedPuzzleIds.length; if(solved < 5) return {label:'Try Chotu Round', action:'start-round', roundId:'chotu_round', note:'Best first session: five easy puzzles.'}; const fav=getFavoriteShopId(); if(fav){ const shop=appState.data.shops.find(s=>s.id===fav); if(shop && getShopSolved(fav)<20) return {label:`Continue ${shop.name}`, action:'open-shop', shopId:fav, note:`Your most played shop has ${20-getShopSolved(fav)} puzzles left.`}; } return {label:'Play Bazaar Mix', action:'start-round', roundId:'bazaar_mix', note:'A 10-puzzle remix from across the bazaar.'}; }
function renderActionButton(action, primary=true){ const cls=primary?'button button-primary':'button button-secondary'; if(action.roundId) return `<button class="${cls}" data-action="${action.action}" data-round-id="${action.roundId}">${escapeHtml(action.label)}</button>`; if(action.shopId) return `<button class="${cls}" data-action="${action.action}" data-shop-id="${action.shopId}">${escapeHtml(action.label)}</button>`; return `<button class="${cls}" data-action="${action.action}">${escapeHtml(action.label)}</button>`; }
function getNextGoals(){ const p=appState.progress; const solved=p.solvedPuzzleIds.length; const goals=[]; const progressText=(done,total)=>`${Math.min(done,total)}/${total}`; if(solved<5) goals.push({name:'Chotu Solver', detail:'Solve 5 puzzles', progress:progressText(solved,5), pct:(solved/5)*100}); else if(solved<15) goals.push({name:'Paheli Intern', detail:'Solve 15 puzzles', progress:progressText(solved,15), pct:(solved/15)*100}); else if(solved<30) goals.push({name:'Bazaar Thinker', detail:'Solve 30 puzzles', progress:progressText(solved,30), pct:(solved/30)*100}); else if(solved<100) goals.push({name:'Bazaar Ustad', detail:'Solve 100 puzzles', progress:progressText(solved,100), pct:(solved/100)*100}); const shopTargets=[['logic_laddoo','Logic Laddoo Taster'],['emoji_puzzle','Emoji Detective'],['word_jumble_paan','Word Paan Champion'],['science_magic','Science Jadugar Junior'],['wrong_answer','Wrong Answer Maharaj']]; shopTargets.forEach(([shopId,name])=>{ const done=getShopSolved(shopId); if(done<10){ const shop=appState.data.shops.find(s=>s.id===shopId); goals.push({name, detail:`Solve 10 in ${shop?.name || shopId}`, progress:progressText(done,10), pct:(done/10)*100}); }}); const dailyDone=p.dailyChallengeHistory.filter(item=>item.solved).length; if(dailyDone<5) goals.push({name:'Daily Bazaar Regular', detail:'Solve 5 daily challenges', progress:progressText(dailyDone,5), pct:(dailyDone/5)*100}); return goals.slice(0,4); }
function renderGoalCards(){ const goals=getNextGoals(); if(!goals.length) return '<p>All current goals completed. New goals can be added in the next content pack.</p>'; return goals.map(goal=>`<div class="goal-card"><div class="progress-label"><span>${escapeHtml(goal.name)}</span><span>${escapeHtml(goal.progress)}</span></div><p>${escapeHtml(goal.detail)}</p><div class="progress-bar"><div style="width:${Math.max(0,Math.min(100,goal.pct))}%"></div></div></div>`).join(''); }
function recordSkippedPuzzle(puzzle){ if(!puzzle) return; addUnique(appState.progress.attemptedPuzzleIds,puzzle.id); addUnique(appState.progress.skippedPuzzleIds,puzzle.id); rememberRecentPuzzle(puzzle.id); const shopStats=ensureShopStats(puzzle.shop); shopStats.attempted += 1; saveProgress(); }

function renderBazaarHome(){ const solved=appState.progress.solvedPuzzleIds.length; const total=appState.data.puzzles.length; const rec=getRecommendedAction(); const cards=appState.data.shops.map(shop=>`<button class="shop-card card" data-action="open-shop" data-shop-id="${shop.id}"><div class="shop-icon">${shop.icon}</div><h2>${escapeHtml(shop.name)}</h2><p class="shopkeeper">${escapeHtml(shop.shopkeeper)}</p><p>${escapeHtml(shop.shortDescription)}</p><p class="progress-text">Solved: ${getShopSolved(shop.id)}/20 · Tried: ${getShopAttempted(shop.id)}</p></button>`).join(''); return `${renderHeader()}<main><section class="home-summary card"><p class="eyebrow">The bazaar is open</p><h1>Which shop will test your dimaag today?</h1><div class="stat-row"><span>🪙 ${appState.progress.coins} coins</span><span>✅ ${solved}/${total} solved</span><span>🔥 ${appState.progress.dailyStreak} streak</span></div><div class="next-action"><div><strong>Suggested next:</strong><p>${escapeHtml(rec.note)}</p></div>${renderActionButton(rec,true)}</div></section><section class="shop-grid">${cards}</section></main>${renderBottomNav('bazaar')}`; }
function renderShopDetail(){ const shop=appState.data.shops.find(item=>item.id===appState.selectedShopId); if(!shop) return renderBazaarHome(); const solved=getShopSolved(shop.id); const quote={paheli_dukaan:'This paheli looks simple. That is why it is dangerous.',emoji_puzzle:'No long speech today. Decode the symbols.',logic_laddoo:'This laddoo has no sugar. Only logic.',word_jumble_paan:'Chew the word slowly. The answer is inside.',mythology_clue:'Every story has a clue. Every clue has a memory.',science_magic:'Magic? No. Science wearing a funny hat.',wrong_answer:'Correct answers are banned here.'}[shop.id] || shop.longDescription; const difficultyLabels={easy:'Easy',medium:'Medium',tricky:'Tricky'}; const difficultyButtons=['easy','medium','tricky'].map(diff=>{ if(isKidMode() && diff==='tricky') return ''; const count=appState.data.puzzles.filter(p=>p.shop===shop.id && p.difficulty===diff).length; if(!count) return ''; return `<button class="button button-secondary" data-action="start-shop-difficulty" data-difficulty="${diff}">${difficultyLabels[diff]} · ${count}</button>`; }).join(''); return `${renderHeader()}<main><section class="card shop-detail"><div class="shop-icon large">${shop.icon}</div><p class="eyebrow">${escapeHtml(shop.shopkeeper)}</p><h1>${escapeHtml(shop.name)}</h1><p><strong>“${escapeHtml(quote)}”</strong></p><p>${escapeHtml(shop.longDescription)}</p><p class="progress-text">Solved: ${solved}/20</p><div class="button-stack"><button class="button button-primary" data-action="start-shop-random">Random Puzzle</button>${difficultyButtons}</div></section></main>${renderBottomNav('bazaar')}`; }
function renderPuzzleScreen(){ const puzzle=appState.activePuzzle; const shop=appState.data.shops.find(item=>item.id===puzzle.shop); const reward=calculateCoins({correct:true,hintsUsed:appState.hintsUsed,inputType:puzzle.inputType}); const roundInfo=appState.mode==='round' ? `<span class="pill">${appState.activeRoundIndex+1}/${appState.activeRoundQueue.length}</span>` : ''; return `${renderHeader()}<main><section class="card puzzle-card"><div class="pill-row" style="justify-content:flex-start"><span class="pill">${shop.icon} ${escapeHtml(shop.name)}</span><span class="pill">${escapeHtml(puzzle.difficulty)}</span>${roundInfo}</div><h1>${escapeHtml(puzzle.title)}</h1><p class="question">${escapeHtml(puzzle.question)}</p><div id="hintArea" class="hint-area">${(appState.shownHints||[]).map((h,i)=>`<div class="hint-card"><strong>Hint ${i+1}</strong><p>${escapeHtml(h)}</p></div>`).join('')}</div><label class="answer-label" for="answerInput">Your answer</label><textarea id="answerInput" class="answer-input" rows="3" placeholder="${puzzle.inputType==='creative' ? 'Write your funniest wrong answer...' : 'Type your answer...'}"></textarea><p class="reward-text">Reward now: ${reward} coins</p><div class="action-row"><button class="button button-secondary" data-action="show-hint">Hint</button><button class="button button-primary" data-action="submit-answer">Submit</button></div><button class="button button-ghost" data-action="skip-puzzle">Skip</button></section></main>${renderBottomNav(null)}`; }
function renderResultScreen(){ const result=appState.result; const puzzle=appState.activePuzzle; const shop=appState.data.shops.find(item=>item.id===puzzle.shop); const reveal = appState.revealed ? `<div class="reveal-box"><h2>Answer</h2><p><strong>${escapeHtml(puzzle.answer || 'Creative answer accepted')}</strong></p><p>${escapeHtml(puzzle.explanation)}</p></div>` : ''; const nextText= appState.mode==='round' ? (appState.activeRoundIndex < appState.activeRoundQueue.length-1 ? 'Next Round Puzzle' : 'Finish Round') : appState.mode==='daily' ? 'Back to Daily' : 'Next Puzzle'; return `${renderHeader()}<main><section class="card result-card ${result.correct?'correct':'wrong'}"><p class="eyebrow">${escapeHtml(shop.name)}</p><h1>${result.correct ? 'Correct!' : 'Not quite.'}</h1><p class="reaction">${escapeHtml(result.reaction)}</p>${result.correct ? `<div class="answer-block"><h2>Answer</h2><p>${escapeHtml(puzzle.answer || 'Creative answer accepted')}</p></div><div class="answer-block"><h2>Why</h2><p>${escapeHtml(puzzle.explanation)}</p></div><p class="coins-earned">Coins earned: +${result.coinsEarned}${result.dailyBonus ? ` · Daily bonus: +${result.dailyBonus}` : ''}</p>` : `<p>The paheli is still hiding.</p>${reveal}`}<div class="button-stack">${result.correct ? `<button class="button button-primary" data-action="next-puzzle">${nextText}</button>` : `<button class="button button-primary" data-action="try-again">Try Again</button><button class="button button-secondary" data-action="reveal-answer">Reveal Answer</button>`}<button class="button button-secondary" data-action="back-bazaar">Back to Bazaar</button><button class="button button-ghost" data-action="share-puzzle">Share</button></div></section></main>${renderBottomNav(null)}`; }
function renderDailyScreen(){ const puzzle=getDailyPuzzle(); const done=hasCompletedDaily(); const history=appState.progress.dailyChallengeHistory.find(item=>item.date===todayString()); return `${renderHeader()}<main><section class="card"><p class="eyebrow">Today’s Bazaar Challenge</p><h1>Daily Challenge</h1><p>One fixed puzzle for today. Solve it to keep your streak alive.</p><div class="stat-row"><span>🔥 ${appState.progress.dailyStreak} streak</span><span>🏆 ${appState.progress.bestDailyStreak} best</span><span>🪙 +25 bonus</span></div><div class="answer-block"><h2>${escapeHtml(puzzle.title)}</h2><p>${escapeHtml(puzzle.question)}</p></div>${done ? `<p class="coins-earned">Today completed: ${history?.solved ? 'Solved' : 'Attempted'}</p><button class="button button-secondary" data-action="enter-bazaar">Back to Bazaar</button>` : `<button class="button button-primary" data-action="start-daily">Start Today’s Puzzle</button>`}</section></main>${renderBottomNav('daily')}`; }
function renderRoundsScreen(){ const cards=appState.data.rounds.map(round=>`<button class="round-card card" data-action="start-round" data-round-id="${round.id}"><h2>${escapeHtml(round.name)}</h2><p>${escapeHtml(round.description)}</p><div class="round-meta"><span>${round.puzzleCount} puzzles</span><span>${round.rewardCoins} round coins</span></div></button>`).join(''); return `${renderHeader()}<main><section class="home-summary card"><p class="eyebrow">Quick game modes</p><h1>Pick a round</h1><p>Rounds remix the same 140 puzzles into quick, repeatable sessions.</p></section><section class="round-grid">${cards}</section></main>${renderBottomNav('rounds')}`; }
function renderRoundResult(){ const s=appState.roundStats || {correct:0,total:0,coins:0}; return `${renderHeader()}<main><section class="card result-card correct"><p class="eyebrow">Round Complete</p><h1>${escapeHtml(appState.data.rounds.find(r=>r.id===appState.selectedRoundId)?.name || 'Round')}</h1><div class="stat-grid"><div>✅ <strong>${s.correct}/${s.total}</strong><span>Correct</span></div><div>🪙 <strong>${s.coins}</strong><span>Coins</span></div><div>🧩 <strong>${new Set(appState.activeRoundQueue.map(p=>p.shop)).size}</strong><span>Shops</span></div></div><div class="button-stack"><button class="button button-primary" data-action="start-round" data-round-id="${appState.selectedRoundId}">Play Again</button><button class="button button-secondary" data-action="open-rounds">Back to Rounds</button></div></section></main>${renderBottomNav('rounds')}`; }
function renderProgressScreen(){ const p=appState.progress; const solved=p.solvedPuzzleIds.length; const total=appState.data.puzzles.length; const accuracy=p.totalAttempts ? Math.round((p.totalCorrect/p.totalAttempts)*100) : 0; const titles=p.earnedTitles.map(titleId=>{ const t=appState.data.titles.find(item=>item.id===titleId); return `<span class="title-badge">${escapeHtml(t?.name || titleId)}</span>`; }).join(''); const shopProgress=appState.data.shops.map(shop=>{ const solvedInShop=getShopSolved(shop.id); return `<div class="shop-progress"><div class="progress-label"><span>${shop.icon} ${escapeHtml(shop.name)}</span><span>${solvedInShop}/20</span></div><div class="progress-bar"><div style="width:${(solvedInShop/20)*100}%"></div></div></div>`; }).join(''); const recentRounds=(p.roundHistory || []).slice(-3).reverse().map(item=>{ const r=appState.data.rounds.find(round=>round.id===item.roundId); return `<div class="mini-history"><strong>${escapeHtml(r?.name || item.roundId)}</strong><span>${item.correct}/${item.total} · ${item.coins} coins</span></div>`; }).join(''); return `${renderHeader()}<main><section class="card"><p class="eyebrow">Bazaar Pass</p><h1>Your progress</h1><div class="stat-grid"><div>🪙 <strong>${p.coins}</strong><span>Coins</span></div><div>✅ <strong>${solved}/${total}</strong><span>Solved</span></div><div>🎯 <strong>${accuracy}%</strong><span>Accuracy</span></div></div><div class="mode-card"><div><strong>Kid Mode</strong><p>${isKidMode() ? 'On: tricky puzzles are avoided in random play, rounds, and daily challenge.' : 'Off: full bazaar difficulty is available.'}</p></div><button class="button button-secondary" data-action="toggle-kid-mode">${isKidMode() ? 'Turn Off' : 'Turn On'}</button></div><h2>Next Goals</h2><div class="goal-list">${renderGoalCards()}</div><h2>Titles</h2><div class="title-list">${titles || '<p>Your first title is waiting.</p>'}</div><h2>Shop Progress</h2>${shopProgress}<h2>Recent Rounds</h2>${recentRounds || '<p>No rounds completed yet.</p>'}<div class="button-stack"><button class="button button-danger" data-action="reset-progress">Reset progress</button></div></section></main>${renderBottomNav('progress')}`; }
function renderApp(){ const app=document.getElementById('app'); const screens={gate:renderGate,bazaar:renderBazaarHome,shop:renderShopDetail,puzzle:renderPuzzleScreen,result:renderResultScreen,daily:renderDailyScreen,rounds:renderRoundsScreen,progress:renderProgressScreen,roundResult:renderRoundResult}; app.innerHTML=(screens[appState.screen]||renderGate)(); }
function startPuzzle(options={}){ appState.activePuzzle=selectPuzzle(options); if(!appState.activePuzzle){ showToast('No puzzle is available for this choice yet. Try Random Puzzle.'); setScreen(appState.selectedShopId ? 'shop' : 'bazaar'); return; } appState.mode=options.mode || 'shop'; appState.selectedDifficulty=options.difficulty || null; appState.hintsUsed=0; appState.shownHints=[]; appState.result=null; appState.revealed=false; setScreen('puzzle'); }
function showHint(){ const puzzle=appState.activePuzzle; if(!puzzle) return; if(appState.hintsUsed >= puzzle.hints.length){ showToast('No more hints. The bazaar has whispered everything.'); return; } const hint=puzzle.hints[appState.hintsUsed]; appState.hintsUsed += 1; appState.shownHints = [...(appState.shownHints || []), hint]; if(appState.screen !== 'puzzle') setScreen('puzzle'); else renderApp(); }
function submitActiveAnswer(){ const input=document.getElementById('answerInput'); const userInput=input ? input.value : ''; if(!userInput.trim()){ showToast('Type an answer first. Even tiny answers are welcome.'); return; } const puzzle=appState.activePuzzle; const correct=checkAnswer(userInput,puzzle); if(!correct && puzzle.inputType==='creative'){ showToast('Ulta Baba says: “Even nonsense needs at least one word.”'); return; } const coinsEarned=calculateCoins({correct,hintsUsed:appState.hintsUsed,inputType:puzzle.inputType}); const reaction=getReaction(puzzle.shop,correct); updateProgressAfterAnswer({puzzle,correct,coinsEarned,userInput}); let dailyBonus=0; if(appState.mode==='daily'){ const wasDone=hasCompletedDaily(); completeDailyChallenge(puzzle.id,correct); if(correct && !wasDone) dailyBonus=25; } if(appState.mode==='round'){ appState.roundStats.total += 1; appState.roundStats.coins += coinsEarned; if(correct) appState.roundStats.correct += 1; }
 appState.result={correct,coinsEarned,dailyBonus,reaction,userInput}; setScreen('result'); }
function nextPuzzle(){ if(appState.mode==='daily'){ setScreen('daily'); return; } if(appState.mode==='round'){ if(appState.activeRoundIndex < appState.activeRoundQueue.length-1){ appState.activeRoundIndex += 1; appState.activePuzzle=appState.activeRoundQueue[appState.activeRoundIndex]; appState.hintsUsed=0; appState.shownHints=[]; appState.result=null; appState.revealed=false; setScreen('puzzle'); } else { const round=appState.data.rounds.find(r=>r.id===appState.selectedRoundId); if(round && appState.roundStats && !appState.roundStats.bonusGiven){ appState.progress.coins += round.rewardCoins; appState.roundStats.coins += round.rewardCoins; appState.roundStats.bonusGiven=true; appState.progress.roundsCompleted += 1; appState.progress.roundHistory.push({roundId:appState.selectedRoundId,date:todayString(),correct:appState.roundStats.correct,total:appState.roundStats.total,coins:appState.roundStats.coins}); saveProgress(); } setScreen('roundResult'); } return; } startPuzzle({shopId:appState.selectedShopId, difficulty:appState.selectedDifficulty || null}); }
function startDaily(){ appState.activePuzzle=getDailyPuzzle(); appState.mode='daily'; appState.selectedDifficulty=null; appState.hintsUsed=0; appState.shownHints=[]; appState.result=null; appState.revealed=false; setScreen('puzzle'); }
function startRound(roundId){ appState.selectedRoundId=roundId; appState.activeRoundQueue=buildRoundQueue(roundId); if(!appState.activeRoundQueue.length){ showToast('This round has no available puzzles yet.'); setScreen('rounds'); return; } appState.activeRoundIndex=0; appState.roundStats={correct:0,total:0,coins:0,bonusGiven:false}; appState.mode='round'; appState.selectedDifficulty=null; appState.activePuzzle=appState.activeRoundQueue[0]; appState.hintsUsed=0; appState.shownHints=[]; appState.result=null; appState.revealed=false; setScreen('puzzle'); }
function skipPuzzle(){ recordSkippedPuzzle(appState.activePuzzle); if(appState.mode==='round'){ if(appState.roundStats){ appState.roundStats.total += 1; } nextPuzzle(); return; } if(appState.mode==='daily'){ setScreen('daily'); return; } startPuzzle({shopId:appState.selectedShopId, difficulty:appState.selectedDifficulty || null}); }
function revealAnswer(){ appState.revealed=true; renderApp(); }
function buildShareText(puzzle,result=null){ if(puzzle.inputType==='creative' && result?.userInput) return `Wrong Answer Only from Paheli Bazaar:\n\n${puzzle.question}\n\nMy answer: ${result.userInput}`; if(result?.correct) return `I solved this Paheli Bazaar puzzle:\n\n${puzzle.question}\n\nAnswer: ${puzzle.answer || result.userInput}`; return `I found this in Paheli Bazaar:\n\n${puzzle.question}\n\nCan you solve it?`; }
async function sharePuzzle(){ const text=buildShareText(appState.activePuzzle,appState.result); try{ if(navigator.share){ await navigator.share({title:'Paheli Bazaar', text}); } else if(navigator.clipboard){ await navigator.clipboard.writeText(text); showToast('Puzzle copied to clipboard.'); } else { showToast('Sharing is not available here.'); } }catch{ showToast('Share cancelled.'); } }
function showToast(message){ const existing=document.querySelector('.toast'); if(existing) existing.remove(); const toast=document.createElement('div'); toast.className='toast'; toast.textContent=message; document.body.appendChild(toast); setTimeout(()=>toast.remove(),2400); }
document.body.addEventListener('click', event=>{ const target=event.target.closest('[data-action]'); if(!target) return; const action=target.dataset.action; if(action==='enter-bazaar') setScreen('bazaar'); if(action==='open-daily') setScreen('daily'); if(action==='open-rounds') setScreen('rounds'); if(action==='open-progress') setScreen('progress'); if(action==='open-shop'){ appState.selectedShopId=target.dataset.shopId; setScreen('shop'); } if(action==='start-shop-random') startPuzzle({shopId:appState.selectedShopId, mode:'shop'}); if(action==='start-shop-difficulty') startPuzzle({shopId:appState.selectedShopId, difficulty:target.dataset.difficulty, mode:'shop'}); if(action==='show-hint') showHint(); if(action==='submit-answer') submitActiveAnswer(); if(action==='skip-puzzle') skipPuzzle(); if(action==='try-again') setScreen('puzzle'); if(action==='next-puzzle') nextPuzzle(); if(action==='back-bazaar') setScreen('bazaar'); if(action==='share-puzzle') sharePuzzle(); if(action==='reveal-answer') revealAnswer(); if(action==='start-daily') startDaily(); if(action==='start-round') startRound(target.dataset.roundId); if(action==='reset-progress') resetProgress(); if(action==='toggle-kid-mode') toggleKidMode(); });
async function initApp(){ try{ await loadAppData(); appState.progress=loadProgress(); if('serviceWorker' in navigator && location.protocol !== 'file:'){ navigator.serviceWorker.register('./service-worker.js').catch(()=>{}); } setScreen('gate'); } catch(error){ document.getElementById('app').innerHTML=`<section class="card"><h1>The bazaar gate is stuck.</h1><p>Please refresh once.</p><pre>${escapeHtml(error.message)}</pre></section>`; } }
initApp();
