#!/usr/bin/env node
// Cloudflare Worker runtime receives a WebAssembly.Module, not a WebAssembly.Instance.
// Patch the wasm-pack bundler glue following Cloudflare's official Rust documentation.
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const dir=process.argv[2]||'worker/pkg';
const file=join(dir,'invariantc.js');
const current=await readFile(file,'utf8');
if (!current.includes('invariantc_bg.wasm') || !current.includes('__wbg_set_wasm')) {
  throw new Error('Unexpected wasm-pack bundler output; verify compatibility before patching');
}
const patch=`// Cloudflare wasm-pack glue, generated by scripts/patch-wasm.mjs.
import * as imports from './invariantc_bg.js';
import wkmod from './invariantc_bg.wasm';
const instance = new WebAssembly.Instance(wkmod, {
  './invariantc_bg.js': imports,
});
imports.__wbg_set_wasm(instance.exports);
export * from './invariantc_bg.js';
`;
await writeFile(file,patch,'utf8');
console.log('Patched wasm-pack bundler glue for Cloudflare Workers per official docs.');
