PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'Parent', tier TEXT NOT NULL DEFAULT 'free', enrolled_class INTEGER NOT NULL DEFAULT 1, subscription_band TEXT DEFAULT 'free', subscription_duration TEXT DEFAULT 'none', subscription_expires_at TEXT, subscription_max_grade INTEGER, admin_login_id TEXT, account_status TEXT NOT NULL DEFAULT 'active', session_version INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS content_registry (id TEXT PRIMARY KEY, title TEXT NOT NULL, subject TEXT NOT NULL, grade_min INTEGER NOT NULL, grade_max INTEGER NOT NULL, chapter TEXT, strand TEXT, icon TEXT DEFAULT '🔬', summary TEXT DEFAULT '', tier_required TEXT NOT NULL, deep_link_url TEXT, status TEXT NOT NULL DEFAULT 'published', preview_json TEXT, protected_json TEXT);
CREATE TABLE IF NOT EXISTS progress (user_id TEXT NOT NULL, content_id TEXT NOT NULL, mastered INTEGER NOT NULL DEFAULT 0, updated_at TEXT DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,content_id));
CREATE TABLE IF NOT EXISTS streaks (user_id TEXT PRIMARY KEY, streak_count INTEGER NOT NULL DEFAULT 0, last_active_date TEXT);
CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, order_id TEXT UNIQUE NOT NULL, amount INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT 'INR', tier_purchased TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'created', gateway TEXT NOT NULL DEFAULT 'razorpay', gateway_payment_id TEXT, gateway_signature TEXT, band TEXT, duration TEXT, base_amount REAL, gst_amount REAL, total_amount REAL, idempotency_key TEXT UNIQUE, webhook_event_id TEXT, refund_status TEXT DEFAULT 'none', refund_amount INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP, verified_at TEXT);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_jti TEXT UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS child_profiles (id TEXT PRIMARY KEY, guardian_id TEXT NOT NULL, display_name TEXT NOT NULL, class_level INTEGER NOT NULL CHECK(class_level BETWEEN 1 AND 10), avatar TEXT DEFAULT '🎓', status TEXT NOT NULL DEFAULT 'active', created_at TEXT DEFAULT CURRENT_TIMESTAMP, deleted_at TEXT);
CREATE TABLE IF NOT EXISTS guardian_relationships (id TEXT PRIMARY KEY, guardian_id TEXT NOT NULL, child_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', verification_method TEXT NOT NULL DEFAULT 'unverified', verified_at TEXT, revoked_at TEXT, verification_evidence TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(guardian_id,child_id));
CREATE TABLE IF NOT EXISTS consent_events (id TEXT PRIMARY KEY, child_id TEXT NOT NULL, guardian_id TEXT, purpose TEXT NOT NULL, action TEXT NOT NULL, notice_version TEXT NOT NULL, recorded_at TEXT DEFAULT CURRENT_TIMESTAMP, evidence_reference TEXT);
CREATE TABLE IF NOT EXISTS classrooms (code TEXT PRIMARY KEY, owner_id TEXT NOT NULL, grade INTEGER NOT NULL CHECK(grade BETWEEN 1 AND 10), status TEXT NOT NULL DEFAULT 'active', created_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(owner_id,grade));
CREATE TABLE IF NOT EXISTS class_rosters (class_code TEXT NOT NULL, student_id TEXT NOT NULL, joined_at TEXT DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(class_code,student_id));
CREATE INDEX IF NOT EXISTS idx_class_rosters_student ON class_rosters(student_id);
CREATE TABLE IF NOT EXISTS parent_linking_codes (id TEXT PRIMARY KEY, child_id TEXT NOT NULL, code_hash TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_parent_link_codes_child ON parent_linking_codes(child_id);
CREATE TABLE IF NOT EXISTS parent_child_relationships (id TEXT PRIMARY KEY, parent_id TEXT NOT NULL, child_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', linked_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(parent_id,child_id));
CREATE INDEX IF NOT EXISTS idx_parent_child_parent ON parent_child_relationships(parent_id);
CREATE INDEX IF NOT EXISTS idx_parent_child_child ON parent_child_relationships(child_id);
CREATE TABLE IF NOT EXISTS quiz_attempts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, content_id TEXT NOT NULL, quiz_session_id TEXT, question_index INTEGER NOT NULL DEFAULT 0, selected_option_index INTEGER, is_correct INTEGER, attempted_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quiz_sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, content_id TEXT NOT NULL, question_indices TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', attempts_count INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 4, expires_at TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, completed_at TEXT);
CREATE TABLE IF NOT EXISTS review_schedule (user_id TEXT NOT NULL, content_id TEXT NOT NULL, box INTEGER NOT NULL DEFAULT 1, next_review_date TEXT NOT NULL, review_count INTEGER NOT NULL DEFAULT 0, last_reviewed_at TEXT, PRIMARY KEY(user_id,content_id));
CREATE TABLE IF NOT EXISTS review_advancement_events (user_id TEXT NOT NULL, content_id TEXT NOT NULL, quiz_session_id TEXT NOT NULL, next_review_date TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,content_id,quiz_session_id));
CREATE TABLE IF NOT EXISTS lab_progress_sync (user_id TEXT NOT NULL, lab_id TEXT NOT NULL, completed_lesson_ids TEXT NOT NULL DEFAULT '[]', last_visited_lesson TEXT, updated_at TEXT DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,lab_id));
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, child_id TEXT NOT NULL, created_by TEXT NOT NULL, period_start TEXT, period_end TEXT, html TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS report_shares (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, title TEXT NOT NULL, html TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP, expires_at TEXT);
CREATE TABLE IF NOT EXISTS report_emails (id TEXT PRIMARY KEY, report_id TEXT NOT NULL, user_id TEXT NOT NULL, email TEXT NOT NULL, subject TEXT NOT NULL, body_html TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, claimed_at TEXT, next_attempt_at TEXT, error TEXT, idempotency_key TEXT UNIQUE, created_at TEXT DEFAULT CURRENT_TIMESTAMP, sent_at TEXT);
CREATE INDEX IF NOT EXISTS idx_report_emails_pending ON report_emails(status,next_attempt_at,claimed_at);
CREATE INDEX IF NOT EXISTS idx_report_shares_user ON report_shares(user_id);
CREATE TABLE IF NOT EXISTS auth_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, token_hash TEXT UNIQUE NOT NULL, purpose TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payment_events (id INTEGER PRIMARY KEY AUTOINCREMENT, gateway_event_id TEXT UNIQUE NOT NULL, event_type TEXT NOT NULL, payload TEXT, processed_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS learning_events (event_id TEXT PRIMARY KEY, user_id TEXT NOT NULL, event_name TEXT NOT NULL, occurred_at TEXT NOT NULL, session_id TEXT NOT NULL, source TEXT NOT NULL, topic_id TEXT, step INTEGER, duration_ms INTEGER, attempt_index INTEGER, independent INTEGER, hint_used INTEGER, outcome TEXT, error_code TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_learning_events_user_time ON learning_events(user_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_learning_events_name ON learning_events(event_name);
CREATE TABLE IF NOT EXISTS deletion_jobs (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'requested', requested_at TEXT DEFAULT CURRENT_TIMESTAMP, completed_at TEXT, details TEXT, attempts INTEGER NOT NULL DEFAULT 0, error TEXT);
CREATE TABLE IF NOT EXISTS progress_blobs (user_id TEXT PRIMARY KEY, blob TEXT NOT NULL, saved_at TEXT, class_code TEXT, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_progress_blobs_class ON progress_blobs(class_code);
CREATE TABLE IF NOT EXISTS security_events (id TEXT PRIMARY KEY, event_type TEXT NOT NULL, subject_hash TEXT, ip_hash TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_security_events_type_time ON security_events(event_type, created_at);
CREATE TABLE IF NOT EXISTS recovery_rate_limits (limiter TEXT NOT NULL, bucket_key TEXT NOT NULL, window_start INTEGER NOT NULL, request_count INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(limiter, bucket_key, window_start));
CREATE INDEX IF NOT EXISTS idx_recovery_rate_limits_window ON recovery_rate_limits(window_start);
CREATE INDEX IF NOT EXISTS idx_content_subject ON content_registry(subject);
CREATE INDEX IF NOT EXISTS idx_content_grade ON content_registry(grade_min,grade_max);
CREATE INDEX IF NOT EXISTS idx_content_tier ON content_registry(tier_required);
CREATE INDEX IF NOT EXISTS idx_progress_user ON progress(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_user ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_quiz_attempt_session_question ON quiz_attempts(user_id, quiz_session_id, question_index) WHERE quiz_session_id IS NOT NULL;
