/* Rasa Engine dialogue catalogue: short original field exchanges that treat knowledge as an accountable practice rather than borrowed scripture. */
export type ExchangeId = "aruna-field" | "laya-interval" | "somavrat-public" | "tara-return" | "margin-cartographer" | "ashram-homecoming" | "confluence-steward" | "tara-unbound" | "observatory-tender" | "tara-lineage" | "surveyor-returns";

export type DialogueExchange = {
  id: ExchangeId;
  speaker: string;
  role: string;
  mark: string;
  lines: string[];
};

export const dialogueExchanges: Record<ExchangeId, DialogueExchange> = {
  "aruna-field": { id: "aruna-field", speaker: "Rishi Aruna", role: "Observation & Shastra", mark: "✧", lines: ["A route begins as a small claim: this is where the water reached; this is when the wind turned.", "Write the condition beside the claim. A reader deserves to know what the instrument could not see.", "Carry the question forward; do not carry certainty farther than the evidence can travel."] },
  "laya-interval": { id: "laya-interval", speaker: "Muni Laya", role: "Practice & Prana", mark: "◌", lines: ["A measured step is not a pause from action. It is the interval that keeps action from becoming force.", "Notice what changes when another traveler keeps the rhythm with you.", "Practice is complete only when it leaves room for someone else to enter the route."] },
  "somavrat-public": { id: "somavrat-public", speaker: "Raja Somavrat", role: "Responsibility & public life", mark: "◇", lines: ["A public instrument is not proven by its precision alone.", "Ask who can read its signal, who is expected to wait, and who bears the cost when the route is wrong.", "A measure becomes responsible when those living with it can still answer back."] },
  "tara-return": { id: "tara-return", speaker: "Tara Vaidyi", role: "Companion & return-line keeper", mark: "⌁", lines: ["A route is not only a line away from home. It is a promise to know how people return.", "Mark the shelter, the tide turn, and the person already caring for the place before a new chart arrives.", "Then the map can travel without pretending it began with us."] },
  "margin-cartographer": { id: "margin-cartographer", speaker: "Margin Cartographer", role: "Mirror Step interlocutor", mark: "◈", lines: ["The open mirror does not ask which source wins. It asks what each source can carry.", "Observation, inference, and testimony become stronger when their limits are still visible beside them.", "Leave a countermark: the next reader may arrive with the condition that changes the route."] },
  "ashram-homecoming": { id: "ashram-homecoming", speaker: "Ashraya Vana", role: "Homecoming study circle", mark: "◒", lines: ["Aruna: bring the source beside your claim. Laya: leave an interval for another reader. Somavrat: let the people on the route answer the record made about them.", "The Ashram does not ask you to return with a finished map. It asks you to return with a more answerable one.", "Ila places the Countermark Lens beside the first field tablet: study, service, and travel now share the same margin."] },
  "confluence-steward": { id: "confluence-steward", speaker: "Confluence Steward", role: "Public-route interlocutor", mark: "◍", lines: ["Three paths can meet without becoming the same path. Set each source beside the condition that gives it reach.", "A public route is useful when its reader can find the return marker before the ground changes beneath them.", "Do not publish a finished world. Publish a route that knows where another traveler may amend it."] },
  "tara-unbound": { id: "tara-unbound", speaker: "Tara Vaidyi", role: "Companion & unbound-line keeper", mark: "⌁", lines: ["The six knots taught us how to return. I will not tie a seventh one for you.", "At this table, name the next reader who must be able to revise the route when its condition shifts.", "That is the unbound line: a map that keeps room for the person still arriving."] },
  "observatory-tender": { id: "observatory-tender", speaker: "Observatory Tender", role: "Return Observatory interlocutor", mark: "◉", lines: ["The earlier route was not a mistake because the river, wind, or shore has changed. It was a measure taken at a condition that had a real reach.", "Set the changed condition beside that earlier line. Let the next reader see what remained useful, what now differs, and where to return with another amendment.", "A lineage is not a chain that closes the route. It is a visible way for care to continue when the ground changes again."] },
  "tara-lineage": { id: "tara-lineage", speaker: "Tara Vaidyi", role: "Companion & unbound-line keeper", mark: "⌁", lines: ["The six knots are still here. They do not need a seventh knot to become a return practice.", "When the river line shifts, carry the old reach beside the new one and ask who must cross it before the next chart is trusted.", "That is how a route remembers without becoming trapped by its first answer."] },
  "surveyor-returns": { id: "surveyor-returns", speaker: "Surveyor of Returns", role: "Living Survey interlocutor", mark: "◌", lines: ["A variance is not a failure of the earlier route. It is a field mark with a different reach.", "Keep its condition, its reader, and the amendment that brought you here visible together.", "Publish the comparison so the next traveler can disagree with care rather than inherit an invisible correction."] },
};
