// Chapter VI design reminder: jade mangrove refuge, star-blue tide channels, and copper listening bowls turn coastal ecology into a shared field practice.
import { ArcRotateCamera } from "@babylonjs/core/Cameras/arcRotateCamera";
import { Color3 } from "@babylonjs/core/Maths/math.color";
import { Vector3 } from "@babylonjs/core/Maths/math.vector";
import { Mesh } from "@babylonjs/core/Meshes/mesh";
import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder";
import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial";
import { Texture } from "@babylonjs/core/Materials/Textures/texture";
import { TransformNode } from "@babylonjs/core/Meshes/transformNode";
import type { Scene } from "@babylonjs/core/scene";
import { AmbientLife } from "./AmbientLife";
import { CinematicCamera } from "./CinematicCamera";
import { HudBridge, type TraitKey } from "./HudBridge";
import { InputManager } from "./InputManager";
import { Player, buildNpcFigure, createPortraitBillboard, type NpcFigure, type PortraitBillboard } from "./Player";
import { SoundFeedback } from "./SoundFeedback";
import { assets } from "./assets";
import type { JourneyContext } from "./scene";

type ListeningBowl = { root: TransformNode; ring: Mesh; heard: boolean; label: string; phase: number };
type Pulse = { ring: Mesh; motes: Mesh[]; age: number };
const saffron = Color3.FromHexString("#F26B38");
const copper = Color3.FromHexString("#B66A35");
const jade = Color3.FromHexString("#3A7968");
const parchment = Color3.FromHexString("#D7B77D");
const tideBlue = Color3.FromHexString("#78BAC8");

export class EstuaryWorld {
  private input = new InputManager();
  private feedback = new SoundFeedback();
  private player: Player;
  private cameraMotion: CinematicCamera;
  private ambient: AmbientLife;
  private bowls: ListeningBowl[] = [];
  private pulses: Pulse[] = [];
  private tideRings: Mesh[] = [];
  private tideGate!: TransformNode;
  private listener!: TransformNode;
  private listenerFigure!: NpcFigure;
  private listenerBillboard!: PortraitBillboard;
  private time = 0;
  private pulseCooldown = 0;
  private heard = 0;
  private stage: "sealed" | "approach" | "listen" | "tide" | "stewardship" | "drill" | "complete" = "approach";
  private traits = { viveka: 48, sahas: 36, karuna: 42 };
  private readonly gatePosition = new Vector3(5.8, 0, -4.7);
  private drillOrder: string[] = [];
  private drillProgress = 0;
  private drillRecord = 0;
  private tideSeason = "Sharad · tidal clarity";
  private newPlus = false;
  private readonly reversedOrder = ["Habitat memory", "Current rhythm", "Salinity trace"];

  constructor(private scene: Scene, private camera: ArcRotateCamera, private hud: HudBridge, private demo: boolean, private context?: JourneyContext) {
    this.newPlus = context?.journeyMode === "new-plus";
    this.createEstuary();
    this.ambient = new AmbientLife(scene, "estuary", () => this.hud.reducedMotion);
    this.player = new Player(scene, new Vector3(-8.2, 0, 7.2), () => this.hud.reducedMotion);
    this.cameraMotion = new CinematicCamera(camera, "estuary", () => this.hud.reducedMotion);
    this.createBowls();
    this.createGateAndListener();
    const unlocked = Boolean(context?.archiveComplete && context?.chapterSixSignal);
    if (!unlocked) this.stage = "sealed";
    this.drillRecord = context?.tideDrillBest ?? 0;
    if (context?.estuaryComplete) { this.stage = "complete"; this.heard = 3; this.bowls.forEach((bowl, index) => { bowl.heard = true; bowl.ring.material = this.mat(`returned-estuary-bowl-${index}`, saffron, saffron); }); }
    this.hud.patch({ chapter: "Chapter VI · The Listening Estuary", questTitle: context?.estuaryComplete ? "The estuary keeps a shared tide record" : unlocked ? this.newPlus ? "The river reaches the listening coast · New Journey+ reversed order" : "The river reaches the listening coast" : "The coast waits for the Archive Shard", questDetail: context?.estuaryComplete ? context.chapterSevenSignal || "The coastal stewardship record has begun its longer journey." : unlocked ? this.newPlus ? "New Journey+ · reversed source order: listen to the bowls in the reversed sequence — Habitat memory, Current rhythm, Salinity trace. The tide flows backward for a returning traveler." : "Reach the tidal observatory and press E to begin listening for salinity, current, and habitat signals." : "Resolve the High-Ridge Archive and carry its shared warning to the coast.", glyphs: context?.estuaryComplete ? 3 : 0, glyphGoal: 3, season: "Sharad · tidal clarity", timeOfDay: "Estuary watch", notice: context?.estuaryComplete ? context.chapterSevenSignal || "Estuary Listener: a tide record becomes public when fishers, mangrove keepers, and the lowest houses can read it together." : this.listenerVoice(), taraBond: context?.taraBond ?? 0, taraArchiveRoute: context?.taraArchiveRoute ?? 0, archiveComplete: context?.archiveComplete ?? false, archiveShard: context?.archiveShard ?? 0, chapterSixSignal: context?.chapterSixSignal ?? "", estuaryUnlocked: unlocked, estuarySignals: context?.estuaryComplete ? 3 : 0, estuaryComplete: context?.estuaryComplete ?? false, mangroveTechnique: context?.mangroveTechnique ?? "", stewardshipChoice: context?.stewardshipChoice ?? "", taraEstuaryRoute: context?.taraEstuaryRoute ?? 0, tideDrillBest: context?.tideDrillBest ?? 0, tideDrillSeason: context?.tideDrillSeason ?? "", chapterSevenSignal: context?.chapterSevenSignal ?? "", materials: { mapFragment: 0, copperFitting: 0, waterReed: 0, shelterCloth: 0, mangroveResin: context?.estuaryComplete ? 1 : 0, saltLeaf: 0 } });
  }

  private mat(name: string, color: Color3, emissive = Color3.Black(), alpha = 1) { const material = new StandardMaterial(name, this.scene); material.diffuseColor = color; material.emissiveColor = emissive; material.specularColor = Color3.Black(); material.alpha = alpha; return material; }
  private createEstuary() {
    const ground = MeshBuilder.CreateGround("estuary-silt-ground", { width: 28, height: 25, subdivisions: 14 }, this.scene); ground.material = this.mat("estuary-silt-mat", Color3.FromHexString("#25383B"), Color3.FromHexString("#0A1417"));
    [-7.1, -2.3, 2.6, 6.5].forEach((x, index) => { const terrace = MeshBuilder.CreateBox(`estuary-tide-step-${index}`, { width: 4.6, height: 0.24 + index * 0.04, depth: 3.3 }, this.scene); terrace.position = new Vector3(x, 0.12 + index * 0.04, 5.8 - index * 3.5); terrace.rotation.y = -0.18; terrace.material = this.mat(`estuary-step-mat-${index}`, index % 2 ? jade : Color3.FromHexString("#C99461"), index % 2 ? Color3.FromHexString("#123B35") : Color3.FromHexString("#44240F")); });
    const path = MeshBuilder.CreateBox("estuary-diagonal-path", { width: 1.2, height: 0.05, depth: 20 }, this.scene); path.position = new Vector3(-0.28, 0.28, 0.15); path.rotation.y = -0.52; path.material = this.mat("estuary-path-mat", parchment, Color3.FromHexString("#38210D"));
    const channel = MeshBuilder.CreateBox("estuary-star-blue-channel", { width: 1.35, height: 0.06, depth: 21.5 }, this.scene); channel.position = new Vector3(-2.9, 0.31, -0.15); channel.rotation.y = -0.52; channel.material = this.mat("estuary-channel-mat", tideBlue, Color3.FromHexString("#164354"), 0.82);
    const backdrop = MeshBuilder.CreatePlane("estuary-visual-target", { width: 32, height: 18 }, this.scene); backdrop.position = new Vector3(0, 7.4, 14.3); backdrop.material = this.mat("estuary-visual-mat", Color3.FromHexString("#102A38"), Color3.FromHexString("#071025"), 0.52); const backMat = backdrop.material as StandardMaterial; backMat.diffuseTexture = new Texture(assets.listeningEstuary, this.scene); backMat.emissiveTexture = new Texture(assets.listeningEstuary, this.scene); backMat.emissiveColor = Color3.FromHexString("#193D4B");
    for (let index = 0; index < 10; index += 1) { const root = new TransformNode(`estuary-mangrove-${index}`, this.scene); root.position = new Vector3(-10 + ((index * 3.7) % 20), 0, index % 2 ? 7.8 : -7.7); const trunk = MeshBuilder.CreateCylinder(`estuary-mangrove-trunk-${index}`, { height: 1.65, diameterTop: 0.13, diameterBottom: 0.24, tessellation: 7 }, this.scene); trunk.parent = root; trunk.position.y = 0.83; trunk.rotation.z = (index % 3 - 1) * 0.2; trunk.material = this.mat(`estuary-mangrove-bark-${index}`, Color3.FromHexString("#6E5139")); const canopy = MeshBuilder.CreateSphere(`estuary-mangrove-canopy-${index}`, { diameter: 1.25, segments: 7 }, this.scene); canopy.parent = root; canopy.position.y = 1.85; canopy.scaling.y = 0.6; canopy.material = this.mat(`estuary-mangrove-leaf-${index}`, Color3.FromHexString(index % 2 ? "#2D7164" : "#3C896F"), Color3.FromHexString("#102D29")); }
  }
  private createBowls() { [[new Vector3(-5.6, 0.3, 2.2), "Salinity trace"], [new Vector3(-0.2, 0.3, -2.8), "Current rhythm"], [new Vector3(5.7, 0.3, 1.5), "Habitat memory"]].forEach(([position, label], index) => { const root = new TransformNode(`estuary-bowl-${index}`, this.scene); root.position.copyFrom(position as Vector3); const base = MeshBuilder.CreateCylinder(`estuary-bowl-base-${index}`, { height: 0.23, diameter: 1.55, tessellation: 24 }, this.scene); base.parent = root; base.position.y = 0.12; base.material = this.mat(`estuary-bowl-base-mat-${index}`, Color3.FromHexString("#24363A")); const bowl = MeshBuilder.CreateTorus(`estuary-bowl-ring-${index}`, { diameter: 1.7, thickness: 0.12, tessellation: 36 }, this.scene); bowl.parent = root; bowl.position.y = 0.98; bowl.rotation.x = Math.PI / 2; bowl.material = this.mat(`estuary-bowl-mat-${index}`, copper, Color3.FromHexString("#351609")); const gauge = MeshBuilder.CreateBox(`estuary-bowl-gauge-${index}`, { width: 1.9, height: 0.05, depth: 0.1 }, this.scene); gauge.parent = root; gauge.position.y = 0.99; gauge.material = this.mat(`estuary-bowl-gauge-mat-${index}`, parchment); this.bowls.push({ root, ring: bowl, heard: false, label: label as string, phase: index * 2.2 }); }); }
  private createGateAndListener() { this.tideGate = new TransformNode("estuary-tide-observatory", this.scene); this.tideGate.position.copyFrom(this.gatePosition); const plinth = MeshBuilder.CreateCylinder("estuary-tide-plinth", { diameter: 3.35, height: 0.26, tessellation: 34 }, this.scene); plinth.parent = this.tideGate; plinth.position.y = 0.13; plinth.material = this.mat("estuary-tide-plinth-mat", Color3.FromHexString("#1B2E34")); [2.8, 1.96, 1.12].forEach((diameter, index) => { const ring = MeshBuilder.CreateTorus(`estuary-tide-ring-${index}`, { diameter, thickness: 0.07, tessellation: 36 }, this.scene); ring.parent = this.tideGate; ring.position.y = 0.42 + index * 0.13; ring.rotation.x = Math.PI / 2; ring.rotation.z = index * 0.6; ring.material = this.mat(`estuary-tide-ring-mat-${index}`, index === 1 ? jade : copper, index === 1 ? Color3.FromHexString("#123A36") : Color3.FromHexString("#331409")); this.tideRings.push(ring); }); const shard = MeshBuilder.CreatePolyhedron("estuary-archive-shard", { type: 1, size: 0.54 }, this.scene); shard.parent = this.tideGate; shard.position.y = 1.15; shard.material = this.mat("estuary-archive-shard-mat", parchment, saffron); this.listener = new TransformNode("estuary-listener", this.scene); this.listener.position = new Vector3(7.5, 0, -5.4); this.listenerFigure = buildNpcFigure({ scene: this.scene, root: this.listener, name: "estuary-listener", robeColor: Color3.FromHexString("#285D5A"), robeHeight: 1.34, robeDiameterTop: 0.46, robeDiameterBottom: 0.72, robeEmissive: Color3.FromHexString("#285D5A").scale(0.05), skinColor: Color3.FromHexString("#A37050"), eyeColor: tideBlue, shawlColor: jade, shawlWidth: 0.74, propColor: copper, propType: "staff", propHeight: 1.5, propRotationZ: -0.18, posture: "leaning", reducedMotion: () => this.hud.reducedMotion }); this.listenerBillboard = createPortraitBillboard(this.scene, this.listener, assets.listeningEstuary, () => this.hud.reducedMotion); }
  update(delta: number) { const step = Math.min(delta, 0.05); const calm = this.hud.reducedMotion; this.time += step; this.pulseCooldown = Math.max(0, this.pulseCooldown - step); this.player.move(this.input.movement(), step, 4.75); this.player.update(step); if (!this.demo && this.input.consumePulse()) this.releasePulse(); if (!this.demo && this.input.consumeInteract()) this.interact(); this.ambient.update(step); this.bowls.forEach((bowl) => { if (!bowl.heard) { bowl.ring.rotation.z += calm ? step * 0.25 : step * 1.2; bowl.root.position.y = calm ? 0.3 : 0.3 + Math.sin(this.time * 1.6 + bowl.phase) * 0.08; } }); this.tideRings.forEach((ring, index) => { ring.rotation.z += step * (index % 2 ? -0.75 : 0.56) * (this.stage === "complete" ? 2 : 1) * (calm ? 0.2 : 1); }); this.listener.position.y = calm ? 0 : Math.sin(this.time * 1.3) * 0.018; this.listenerFigure.update(step, this.time); this.listenerBillboard.update(this.player.root.position, this.camera.position); this.pulses = this.pulses.filter((pulse) => { pulse.age += step; pulse.ring.scaling.setAll(1 + pulse.age * 8); (pulse.ring.material as StandardMaterial).alpha = Math.max(0, 0.88 - pulse.age * 0.88); pulse.motes.forEach((mote, index) => { const angle = (Math.PI * 2 * index) / pulse.motes.length; mote.position.x += Math.cos(angle) * step * 2; mote.position.z += Math.sin(angle) * step * 2; mote.position.y += step * 0.72; mote.scaling.setAll(Math.max(0.05, 1 - pulse.age)); }); if (pulse.age > 1) { pulse.ring.dispose(); pulse.motes.forEach((mote) => mote.dispose()); return false; } return true; }); this.cameraMotion.update(step, this.player, this.stage === "tide" || this.stage === "stewardship" || this.stage === "complete" ? this.gatePosition : this.stage === "listen" ? this.bowls.find((bowl) => !bowl.heard)?.root.position : undefined, this.input); this.hud.patch({ pulseReady: this.pulseCooldown <= 0 }); }
  private releasePulse() { if (this.pulseCooldown > 0) return; this.pulseCooldown = 1.45; const ring = MeshBuilder.CreateTorus("estuary-focus-pulse", { diameter: 0.86, thickness: 0.07, tessellation: 38 }, this.scene); ring.position = this.player.root.position.clone(); ring.position.y = 0.28; ring.rotation.x = Math.PI / 2; ring.material = this.mat("estuary-pulse-mat", saffron, saffron, 0.88); const motes = Array.from({ length: 14 }, (_, index) => { const mote = MeshBuilder.CreateSphere(`estuary-pulse-mote-${index}`, { diameter: 0.09, segments: 6 }, this.scene); const angle = (Math.PI * 2 * index) / 14; mote.position = ring.position.add(new Vector3(Math.cos(angle) * 0.5, 0.04, Math.sin(angle) * 0.5)); mote.material = this.mat(`estuary-pulse-mote-mat-${index}`, saffron, saffron); return mote; }); this.pulses.push({ ring, motes, age: 0 }); this.cameraMotion.emphasize(); if (!this.demo) this.feedback.pulse(); if (this.stage !== "listen") { this.hud.patch({ notice: this.stage === "sealed" ? "The estuary needs the Archive’s shared warning before it can listen." : "At the coast, focus pulses become evidence only after the tide observatory has been opened." }); return; } const bowl = this.bowls.find((entry) => !entry.heard && Vector3.Distance(entry.root.position, this.player.root.position) < 3.8); if (!bowl) { this.hud.patch({ notice: "Stand by an unrecorded listening bowl. Salinity, current, and habitat must each become a usable signal." }); return; } if (this.newPlus) { const expected = this.reversedOrder[this.heard]; if (bowl.label !== expected) { this.hud.patch({ notice: `New Journey+ · reversed order: ${bowl.label} arrived too early. The reversed tide begins with ${expected}.` }); if (!this.demo) this.feedback.speak(); return; } } bowl.heard = true; bowl.ring.material = this.mat(`estuary-bowl-heard-${this.heard}`, saffron, saffron); this.heard += 1; if (!this.demo) this.feedback.collect(); if (this.heard === 3) { this.stage = "tide"; this.hud.patch({ glyphs: 3, estuarySignals: 3, questTitle: "Open the tide window", questDetail: "Return to the tidal observatory and press E. Archive Shard, Rainward Current, and Measured Step will carry the three signals across the tide.", notice: "Estuary Listener: all three signals agree. Now decide whether the tide can move without leaving its smallest refuge behind." }); } else this.hud.patch({ glyphs: this.heard, estuarySignals: this.heard, notice: this.newPlus ? `${bowl.label} recorded in reversed order. Next: ${this.reversedOrder[this.heard]}.` : `${bowl.label} is audible. The coast still needs ${3 - this.heard} signal${3 - this.heard === 1 ? "" : "s"}.` }); }
  private interact() {
    if (this.stage === "sealed") { this.hud.patch({ notice: "Estuary Listener: bring the Archive Shard after the ridge has made its warning public." }); return; }
    if (this.stage === "approach" && Vector3.Distance(this.player.root.position, this.gatePosition) < 3.2) { this.stage = "listen"; if (!this.demo) this.feedback.speak(); this.hud.patch({ questTitle: "Listen to the tide bowls", questDetail: "Use focus pulses at salinity, current, and habitat bowls. A coast is not one signal but a shared measure.", glyphs: 0, glyphGoal: 3, notice: `${this.listenerVoice()} The Listener opens the observatory and asks what a tide record must protect before it is useful.` }); return; }
    if (this.stage === "tide" && Vector3.Distance(this.player.root.position, this.gatePosition) < 3.2) { this.openTideWindow(); return; }
    if (this.stage === "complete" && Vector3.Distance(this.player.root.position, this.gatePosition) < 3.2) { this.startTideDrill(); return; }
    if (this.stage === "drill") { this.recordDrillBowl(); return; }
    if (Vector3.Distance(this.player.root.position, this.listener.position) < 3.2) { this.feedback.speak(); this.hud.patch({ notice: `${this.listenerVoice()} The coast refuses a forecast that treats habitat as scenery rather than the condition of someone’s home.` }); }
  }
  private startTideDrill() {
    const orders = [["Salinity trace", "Current rhythm", "Habitat memory"], ["Current rhythm", "Habitat memory", "Salinity trace"], ["Habitat memory", "Salinity trace", "Current rhythm"]];
    const index = this.tideSeason.includes("Varsha") ? 1 : this.tideSeason.includes("Shishira") ? 2 : 0;
    this.drillOrder = orders[index]; this.drillProgress = 0; this.stage = "drill";
    this.bowls.forEach((bowl, bowlIndex) => { bowl.heard = false; bowl.ring.material = this.mat(`estuary-drill-reset-${bowlIndex}`, copper, Color3.FromHexString("#351609")); });
    this.hud.patch({ glyphs: 0, glyphGoal: 3, questTitle: "Seasonal tide drill", questDetail: `Record the bowls in this ${this.tideSeason.split(" · ")[0]} order: ${this.drillOrder.join(" → ")}. Stand by each bowl and press E.`, tideDrillSeason: this.tideSeason, notice: "Estuary Listener: the coast changes its order with the season; a replayed practice is useful only when it remains attentive." });
  }
  private recordDrillBowl() {
    const bowl = this.bowls.find((entry) => !entry.heard && Vector3.Distance(entry.root.position, this.player.root.position) < 3.8);
    if (!bowl) { this.hud.patch({ notice: "Stand beside the next unrecorded tide bowl and press E to place it in the seasonal sequence." }); return; }
    const expected = this.drillOrder[this.drillProgress];
    if (bowl.label !== expected) { this.hud.patch({ notice: `${bowl.label} arrived too early. The seasonal sequence still begins with ${expected}.` }); if (!this.demo) this.feedback.speak(); return; }
    bowl.heard = true; bowl.ring.material = this.mat(`estuary-drill-aligned-${this.drillProgress}`, saffron, saffron); this.drillProgress += 1;
    if (!this.demo) this.feedback.collect();
    if (this.drillProgress === 3) { this.stage = "complete"; this.drillRecord += 1; this.hud.patch({ glyphs: 3, tideDrillBest: this.drillRecord, tideDrillSeason: this.tideSeason, milestone: `Tide drill · ${this.tideSeason.split(" · ")[0]} sequence recorded`, questTitle: "The tide drill is carried", questDetail: `Seasonal sequence ${this.drillRecord} recorded. Return to the observatory later to practice another tide order.`, notice: "Tara: the best route plan is not the fastest one; it is the one that still remembers the water will change." }); }
    else this.hud.patch({ glyphs: this.drillProgress, tideDrillBest: this.drillRecord, notice: `${bowl.label} recorded. Next: ${this.drillOrder[this.drillProgress]}.` });
  }
  private openTideWindow() { const canOpen = Boolean(this.context?.archiveShard && this.context?.advancedTechnique && this.context?.measuredStep); if (!canOpen) { this.hud.patch({ notice: "The tide window needs the Archive Shard, Rainward Current, and Measured Step. Carry each practice into the coast before asking the water to move." }); return; } this.stage = "stewardship"; if (!this.demo) this.feedback.align(); this.hud.patch({ choiceOpen: true, choiceMode: "stewardship", questTitle: "Choose the coast’s first shared measure", questDetail: "The tide window is open. Which stewardship promise should the Estuary Listener record?", notice: "The Archive Shard refracts through the tide window. Tara asks whose return route will remain possible after the water turns." }); }
  chooseStance = (trait: TraitKey) => { if (this.stage !== "stewardship") return; this.stage = "complete"; const choices: Record<TraitKey, string> = { viveka: "Fishing access is charted beside tide conditions, so small crews can read a safe return without being priced out of the signal.", sahas: "Mangrove habitat restoration receives the first measured crossing, protecting the roots that soften the next storm.", karuna: "Flood readiness becomes the first coastal route, carrying the tide signal to the lowest homes before private docks." }; const chapterSevenSignal = trait === "viveka" ? "Chapter VII · The Salt Library answers: bring the shared tide chart to a coast where trade has forgotten who can read the water." : trait === "sahas" ? "Chapter VII · The Salt Library answers: the restored roots carry a record older than the observatory; follow their surviving line." : "Chapter VII · The Salt Library answers: a shelter map has reached the sea wall; carry it to the people who cannot wait for high ground."; if (!this.demo) this.feedback.align(); this.hud.patch({ choiceOpen: false, estuaryComplete: true, estuarySignals: 3, mangroveTechnique: "Mangrove Refuge", stewardshipChoice: choices[trait], taraBond: 5, taraEstuaryRoute: 1, chapterSevenSignal, milestone: "Mangrove Refuge · tide shelter carried", questTitle: "The estuary keeps a shared tide record", questDetail: chapterSevenSignal, notice: `${choices[trait]} Tara ties a fifth knot: a coastal route must remember the living shore that holds it.` , materials: { mapFragment: 0, copperFitting: 0, waterReed: 0, shelterCloth: 0, mangroveResin: 1, saltLeaf: 0 } }); };
  private listenerVoice() { if (this.context?.saltLibraryComplete) return "Estuary Listener: the Salt Library returned your tide chart with its margins open. The coast recognizes a record that can still listen after it has traveled."; if (!this.context?.chapterSixSignal) return "Estuary Listener: The coast can only hear a warning after someone carries it here."; if (this.context.chapterSixSignal.includes("passage")) return "Estuary Listener: You carried a warning about passage. Here, every current asks whose boat can return when the tide decides otherwise."; if (this.context.chapterSixSignal.includes("shelter")) return "Estuary Listener: You carried shelter to the coast. Here, the mangrove roots ask whether that shelter includes the water itself."; return "Estuary Listener: The Archive spoke of public warning. Here, the tide asks whether an early signal can also protect the people who live at its edge."; }
  advanceSeason = () => { const season = this.ambient.advanceSeason(); this.tideSeason = season; this.hud.patch({ season, tideDrillSeason: season, notice: `${season} changes the estuary motes and current color; completed routes can now open a different seasonal tide-drill order.` }); };
  advanceTime = () => { const time = this.ambient.advanceTime(); this.hud.patch({ timeOfDay: time, notice: `${time} shifts the reflection on the tide gauge. Measured Step keeps the observation from becoming a guess.` }); };
  inquireGuide = (guide: "rishi" | "muni" | "raja") => { const notes = { rishi: this.context?.returnObservatoryComplete ? "Aruna’s Observatory return note: the salinity window keeps its earlier shore reach beside the changed access condition, rather than asking the tide to have one final reader." : this.context?.confluenceComplete ? "Aruna’s estuary return note: the shore record now carries its salinity window and a return condition rather than pretending the tide has one fixed reader." : "Aruna’s estuary note: a tide forecast can be precise and still be falsely certain about the people it leaves out.", muni: this.context?.returnObservatoryComplete ? "Laya’s Observatory return note: the amendment leaves a calm interval for the next tide watcher to place a changed crossing beside the older line." : this.context?.confluenceComplete ? "Laya’s estuary return note: the route braid keeps a calm interval where the next tide watcher can enter the record." : "Laya’s estuary note: collective calm is not stillness; it is the practiced rhythm of moving together when water rises.", raja: `Somavrat’s estuary note: ${this.context?.amendmentChoice || this.context?.publicRouteChoice || this.context?.publicChoice || "stewardship begins when a coast can use the record made about it."}` }; this.hud.patch({ notice: notes[guide] }); };
  dispose() { this.input.dispose(); this.player.dispose(); this.feedback.dispose(); this.ambient.dispose(); this.listenerBillboard.dispose(); this.pulses.forEach((pulse) => { pulse.ring.dispose(); pulse.motes.forEach((mote) => mote.dispose()); }); }
}
