import {runIntelligence,endpointLabel} from '../core/ai-adapter.js';
import {challengeUrl,shareResult} from '../core/share.js';
import {discoveryVisual,fusionLineageLayout} from '../core/play-systems.js';
export const meta={id:'fusion-lab',emoji:'🧪',title:'Combine Anything',tagline:'Build a discovery chain, then navigate the branching lineage you created.',verb:'Fuse',presentation:'Visual discovery reactor + clickable branching lineage + earned Three.js'};
const START=['Earth','Water','Fire','Wind'];const THREE_URL='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.180.0/three.module.min.js';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export function mount(root,ctx,challenge){
  const discoveries=[...START];let slots=[String(challenge?.a||'Water').slice(0,80),String(challenge?.b||'Fire').slice(0,80)],busy=false,timer=0,chain=0,alive=true,threeCleanup=()=>{},lineage=[];
  root.innerHTML=`<section class="game-head"><div><span class="eyebrow">${meta.verb}</span><h1>${meta.emoji} ${meta.title}</h1><p>${meta.tagline}</p></div><span class="engine-pill">${endpointLabel()} · discovery chain</span></section><article class="play-card fusion-card"><div class="fusion-chain"><span>Chain</span><strong id="chain">0 / 3</strong><small id="unlockHint">${ctx.hasUnlock('reactor-3d')?'3D reactor unlocked':'Chain three discoveries to unlock the optional 3D reactor.'}</small></div><div class="fusion-workbench"><div class="reactor-slot" data-slot="0"><span>Drop A</span></div><div class="fusion-reactor" id="reactor"><div class="reactor-visual" id="reactorVisual"><div class="reactor-core">✦</div></div><button type="button" class="primary" id="combine">FUSE</button><button type="button" class="reactor-mode secondary" id="reactorMode" ${ctx.hasUnlock('reactor-3d')?'':'disabled'}>${ctx.hasUnlock('reactor-3d')?'3D reactor':'3D locked'}</button></div><div class="reactor-slot" data-slot="1"><span>Drop B</span></div></div><div class="custom-discovery"><input id="custom" maxlength="80" placeholder="Add any custom thing…"><button class="secondary" type="button" id="addCustom">Add</button></div><section class="discovery-field"><div class="discovery-head"><span class="result-kicker">Discovery field</span><small>Tap a bubble or drag it into a reactor slot.</small></div><div id="discoveries" class="discovery-bubbles"></div></section><section class="lineage-panel"><div class="discovery-head"><span class="result-kicker">Fusion lineage</span><small>Every fusion becomes a branch. Tap a node to reuse it.</small></div><div class="lineage-scroll"><div class="lineage-canvas" id="lineage"></div></div></section><div id="result" aria-live="polite"></div></article>`;
  const field=root.querySelector('#discoveries'),reactor=root.querySelector('#reactor'),combine=root.querySelector('#combine'),result=root.querySelector('#result'),slotEls=[...root.querySelectorAll('.reactor-slot')],chainEl=root.querySelector('#chain'),hint=root.querySelector('#unlockHint'),modeButton=root.querySelector('#reactorMode'),visual=root.querySelector('#reactorVisual'),lineageEl=root.querySelector('#lineage');let threeOn=false;
  function assign(item){const i=!slots[0]?0:!slots[1]?1:0;slots[i]=item;render();ctx.ping('ok');}
  function bubbleMarkup(item,compact){const v=discoveryVisual(item);return `<span class="bubble-visual ${compact?'compact':''}" style="--h:${v.hue};--h2:${v.hue2};--s:${v.size}px;--spin:${v.spin}deg"><i>${v.glyph}</i><b>${esc(item)}</b></span>`;}
  function renderLineage(){const layout=fusionLineageLayout(lineage,START);lineageEl.style.width=`${layout.width}px`;lineageEl.style.height=`${Math.max(130,layout.height)}px`;const lines=`<svg viewBox="0 0 ${layout.width} ${Math.max(130,layout.height)}" aria-hidden="true">${layout.links.map(l=>`<path d="M ${l.x1} ${l.y1+18} C ${l.x1} ${l.y1+52}, ${l.x2} ${l.y2-52}, ${l.x2} ${l.y2-18}" />`).join('')}</svg>`;const nodes=layout.nodes.map(n=>{const v=discoveryVisual(n.name);return `<button type="button" class="lineage-node depth-${n.depth}" data-lineage="${esc(n.name)}" style="left:${n.x}px;top:${n.y}px;--h:${v.hue}"><span>${v.glyph}</span><b>${esc(n.name)}</b></button>`;}).join('');lineageEl.innerHTML=lines+nodes;lineageEl.querySelectorAll('[data-lineage]').forEach(b=>b.onclick=()=>{assign(b.dataset.lineage);ctx.ping('ok');});}
  function render(){slotEls.forEach((el,i)=>{const item=slots[i];el.classList.toggle('filled',!!item);el.innerHTML=item?bubbleMarkup(item,true):'<span>Drop item</span>';});combine.disabled=!slots[0]||!slots[1]||busy;field.innerHTML=discoveries.map(x=>`<button type="button" draggable="true" data-item="${esc(x)}" class="discovery-bubble">${bubbleMarkup(x,false)}</button>`).join('');field.querySelectorAll('[data-item]').forEach(b=>{b.onclick=()=>assign(b.dataset.item);b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.item));});chainEl.textContent=`${Math.min(chain,3)} / 3`;renderLineage();}
  slotEls.forEach((el,i)=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();slots[i]=e.dataTransfer.getData('text/plain').slice(0,80);render();});el.onclick=()=>{if(slots[i]){slots[i]='';render();}};});root.querySelector('#addCustom').onclick=()=>{const input=root.querySelector('#custom'),x=input.value.trim();if(!x)return;if(!discoveries.includes(x))discoveries.push(x);input.value='';assign(x);};
  async function startThree(){if(threeOn||!ctx.hasUnlock('reactor-3d')||document.documentElement.classList.contains('reduce-motion'))return;modeButton.disabled=true;modeButton.textContent='Loading 3D…';try{const THREE=await Promise.race([import(THREE_URL),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),3000))]);if(!alive)return;threeCleanup();visual.innerHTML='';const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,20);camera.position.set(0,0,4);const renderer=new THREE.WebGLRenderer({alpha:true,antialias:ctx.quality!=='low'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,ctx.quality==='high'?2:1.4));renderer.setSize(140,140,false);renderer.domElement.className='mini-reactor-canvas';visual.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xaadfff,0x201018,2.4));const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.7,2),new THREE.MeshStandardMaterial({color:0xffcc66,emissive:0x6b3d12,emissiveIntensity:1.1,roughness:.35,metalness:.15}));scene.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.045,8,48),new THREE.MeshBasicMaterial({color:0x8de0d2,transparent:true,opacity:.8}));ring.rotation.x=1.1;scene.add(ring);const ring2=ring.clone();ring2.material=ring.material.clone();ring2.material.color.set(0xff7d91);ring2.rotation.y=1.2;scene.add(ring2);let raf=0;const loop=()=>{if(!alive||!threeOn)return;core.rotation.x+=.008;core.rotation.y+=.014;ring.rotation.z+=.012;ring2.rotation.x+=.01;renderer.render(scene,camera);raf=requestAnimationFrame(loop);};threeOn=true;modeButton.disabled=false;modeButton.textContent='Use 2D reactor';loop();threeCleanup=()=>{threeOn=false;cancelAnimationFrame(raf);core.geometry.dispose();core.material.dispose();ring.geometry.dispose();ring.material.dispose();ring2.geometry.dispose();ring2.material.dispose();renderer.dispose();renderer.domElement.remove();};}catch(e){console.warn('Fusion 3D reactor unavailable',e);modeButton.disabled=false;modeButton.textContent='3D unavailable';visual.innerHTML='<div class="reactor-core">✦</div>';}}
  function stopThree(){if(!threeOn)return;threeCleanup();visual.innerHTML='<div class="reactor-core">✦</div>';modeButton.textContent='3D reactor';modeButton.disabled=false;}
  modeButton.onclick=()=>threeOn?stopThree():startThree();
  combine.onclick=async()=>{if(busy||!slots[0]||!slots[1])return;busy=true;render();const [a,b]=slots;reactor.classList.add('fusing');result.innerHTML='';const r=await runIntelligence('combine',{a,b});timer=setTimeout(()=>{reactor.classList.remove('fusing');if(!discoveries.includes(r.result))discoveries.push(r.result);lineage.push({a,b,result:r.result});slots=[r.result,''];busy=false;chain++;if(chain>=3){const award=ctx.award('chain-reaction');if(ctx.hasUnlock('reactor-3d')){modeButton.disabled=false;modeButton.textContent=threeOn?'Use 2D reactor':'3D reactor';hint.textContent='3D reactor unlocked. It remains optional and can fall back to 2D.';if(award.changed)startThree();}}render();result.innerHTML=`<article class="result-card fusion-result"><span class="result-kicker">New discovery</span>${bubbleMarkup(r.result,false)}<p>${esc(r.note)}</p><div class="result-actions"><button class="secondary" id="branch">Fuse it again</button><button class="primary" id="share">Challenge pair</button></div></article>`;ctx.record(`${a} + ${b} = ${r.result}`);ctx.ping('pop');result.querySelector('#branch').onclick=()=>{ctx.replay();root.querySelector('#custom').focus();};result.querySelector('#share').onclick=async()=>ctx.shared(await shareResult({title:meta.title,text:`What do you get from ${a} + ${b}?`,url:challengeUrl(meta.id,{a,b})}));},620);};
  render();if(ctx.hasUnlock('reactor-3d'))modeButton.disabled=false;if(challenge?.a&&challenge?.b)queueMicrotask(()=>combine.click());return()=>{alive=false;clearTimeout(timer);threeCleanup();};
}
