import {runIntelligence,endpointLabel} from '../core/ai-adapter.js';
import {challengeUrl,shareResult} from '../core/share.js';
import {buildJugaadPlan,jugaadSynergy,visualIdentity,jugaadSimulation,jugaadSpatialBonus} from '../core/play-systems.js';
export const meta={id:'jugaad',emoji:'🧰',title:'Jugaad Challenge',tagline:'Place tools in space, connect a contraption, then test whether it reaches the target.',verb:'Build',presentation:'Spatial 2D construction bench + target simulation'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const SCENARIOS=[
 {place:'You are locked on a rooftop during a sudden rainstorm.',icon:'🌧️',target:'Reach the stairwell',items:['umbrella','pressure cooker','shoelace','₹20 coin'],goal:'🚪'},
 {place:'Your bicycle chain snaps 4 km from home.',icon:'🚲',target:'Get the bicycle moving',items:['newspaper','water bottle','rubber band','spoon'],goal:'🏠'},
 {place:'A monkey has taken your phone and is sitting on a wall.',icon:'🐒',target:'Recover the phone',items:['banana','mirror','scarf','empty lunchbox'],goal:'📱'},
 {place:'The power goes out ten minutes before an online interview.',icon:'💻',target:'Get online somehow',items:['old phone','torch','steel plate','extension cable'],goal:'📶'},
 {place:'Your team must move a giant cardboard box through a tiny doorway.',icon:'📦',target:'Move the box through',items:['rope','soap','two chairs','marker pen'],goal:'🚪'}
];
const STRATEGIES=[['build','🔧 Build'],['distract','🎭 Distract'],['signal','📣 Signal'],['leverage','⚙ Leverage']];
export function mount(root,ctx,challenge){
  const scenarioIndex=Number.isInteger(challenge?.scenarioIndex)?Math.max(0,Math.min(SCENARIOS.length-1,challenge.scenarioIndex)):Math.floor(ctx.dailySeed*SCENARIOS.length)%SCENARIOS.length,s=SCENARIOS[scenarioIndex];
  let placements=[],armed=null,strategy='build',running=false,timers=[];const stabilizer=ctx.hasUnlock('prototype-bench');
  root.innerHTML=`<section class="game-head"><div><span class="eyebrow">${meta.verb}</span><h1>${meta.emoji} ${meta.title}</h1><p>${meta.tagline}</p></div><span class="engine-pill">${endpointLabel()} · position-sensitive local simulation</span></section>
  <article class="play-card jugaad-card"><section class="jugaad-scene"><div class="scenario-visual"><span>${s.icon}</span><div><b>${esc(s.target)}</b><small>${esc(s.place)}</small></div><div class="target-track"><div class="target-agent" id="targetAgent">🛠️</div><div class="target-goal">${s.goal}</div><div class="target-fill" id="targetFill"></div></div></div>
  <div class="build-bench spatial-bench ${stabilizer?'prototype':''}" id="bench"><div class="bench-top"><span class="bench-label">${armed?`Place ${esc(armed)}`:'Select a tool, then tap a grid cell'} ${stabilizer?'· stabilizer active':''}</span><span id="spatialReadout">Spatial bonus 0</span></div><svg class="bench-links" id="benchLinks" viewBox="0 0 600 300" aria-hidden="true"></svg><div class="bench-grid" id="benchGrid">${Array.from({length:18},(_,i)=>`<button type="button" data-cell="${i}" aria-label="Construction cell ${i+1}"></button>`).join('')}</div></div></section>
  <div class="inventory interactive-inventory" id="inventory">${s.items.map((x,i)=>`<button type="button" draggable="true" data-item="${esc(x)}" data-i="${i}">${esc(x)}</button>`).join('')}</div>
  <div class="strategy-row" id="strategies">${STRATEGIES.map(([id,label],i)=>`<button type="button" data-strategy="${id}" class="${i===0?'selected':''}">${label}</button>`).join('')}</div>
  <div class="jugaad-actions"><div><span class="result-kicker">Bench synergy</span><strong id="synergy">0</strong></div><button class="secondary" type="button" id="clear">Clear bench</button><button class="primary" type="button" id="test" disabled>Run target test</button></div><div class="sim-log" id="simLog" aria-live="polite"></div><div id="result" aria-live="polite"></div></article>`;
  const inv=root.querySelector('#inventory'),grid=root.querySelector('#benchGrid'),test=root.querySelector('#test'),synergy=root.querySelector('#synergy'),result=root.querySelector('#result'),fill=root.querySelector('#targetFill'),agent=root.querySelector('#targetAgent'),simLog=root.querySelector('#simLog'),links=root.querySelector('#benchLinks'),readout=root.querySelector('#spatialReadout'),label=root.querySelector('.bench-label');
  const xy=i=>({x:i%6,y:Math.floor(i/6)}),idx=(x,y)=>y*6+x;
  function selectedItems(){return placements.map(p=>p.item);}
  function place(item,x,y){if(!item||running)return;placements=placements.filter(p=>p.item!==item&&!(p.x===x&&p.y===y));if(placements.length>=3)return;placements.push({item,x,y});armed=null;render();ctx.ping('ok');}
  function renderLinks(){if(placements.length<2){links.innerHTML='';return;}const pts=placements.map(p=>({x:p.x*100+50,y:p.y*100+50}));links.innerHTML=pts.slice(1).map((p,i)=>`<line x1="${pts[i].x}" y1="${pts[i].y}" x2="${p.x}" y2="${p.y}" />`).join('');}
  function render(){const items=selectedItems(),spatial=jugaadSpatialBonus(placements,strategy,scenarioIndex);label.textContent=armed?`Place ${armed} on the grid`:`Select a tool, then tap a grid cell${stabilizer?' · stabilizer active':''}`;readout.textContent=`Spatial +${spatial.bonus} · ${spatial.description}`;grid.querySelectorAll('[data-cell]').forEach((cell,i)=>{const {x,y}=xy(i),p=placements.find(q=>q.x===x&&q.y===y);cell.classList.toggle('filled',!!p);cell.innerHTML=p?(()=>{const v=visualIdentity(p.item);return `<span class="bench-piece" style="--h:${v.hue}"><i>${v.glyph}</i><small>${esc(p.item)}</small></span>`;})():'';cell.title=p?`Remove ${p.item}`:(armed?`Place ${armed}`:'Empty construction cell');});inv.querySelectorAll('[data-item]').forEach(b=>{const used=items.includes(b.dataset.item);b.classList.toggle('used',used);b.classList.toggle('armed',armed===b.dataset.item);b.disabled=used||running;});synergy.textContent=items.length?Math.min(100,jugaadSynergy(items,strategy)+spatial.bonus):0;test.disabled=items.length<2||running;renderLinks();}
  inv.querySelectorAll('[data-item]').forEach(b=>{b.onclick=()=>{if(b.disabled)return;armed=armed===b.dataset.item?null:b.dataset.item;render();ctx.ping('ok');};b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.item));});
  grid.querySelectorAll('[data-cell]').forEach((cell,i)=>{const {x,y}=xy(i);cell.addEventListener('dragover',e=>e.preventDefault());cell.addEventListener('drop',e=>{e.preventDefault();place(e.dataTransfer.getData('text/plain'),x,y);});cell.onclick=()=>{const p=placements.find(q=>q.x===x&&q.y===y);if(p){placements=placements.filter(q=>q!==p);armed=p.item;render();ctx.ping('ok');return;}if(armed)place(armed,x,y);};});
  root.querySelector('#clear').onclick=()=>{if(running)return;placements=[];armed=null;result.innerHTML='';simLog.innerHTML='';fill.style.width='0%';agent.style.left='2%';render();};
  root.querySelectorAll('[data-strategy]').forEach(b=>b.onclick=()=>{if(running)return;strategy=b.dataset.strategy;root.querySelectorAll('[data-strategy]').forEach(x=>x.classList.toggle('selected',x===b));render();ctx.ping('ok');});
  test.onclick=async()=>{const items=selectedItems();if(items.length<2||running)return;running=true;render();fill.style.width='0%';agent.style.left='2%';simLog.innerHTML='';result.innerHTML='';const sim=jugaadSimulation(scenarioIndex,items,strategy,placements);if(stabilizer){sim.progress=Math.min(100,sim.progress+5);sim.steps.push({item:'prototype stabilizer',delta:5,label:'prototype stabilizer adds 5%'});}const plan=buildJugaadPlan(items,strategy,s.place),flavor=await runIntelligence('jugaad',{scenario:s,solution:plan});let acc=0;const reduced=document.documentElement.classList.contains('reduce-motion');sim.steps.forEach((step,i)=>{timers.push(setTimeout(()=>{acc=Math.min(sim.progress,acc+step.delta);fill.style.width=`${acc}%`;agent.style.left=`calc(${Math.max(2,Math.min(93,acc))}% - 18px)`;simLog.innerHTML+=`<p><b>+${step.delta}%</b> ${esc(step.label)}</p>`;ctx.ping('ok');},reduced?0:160+i*230));});timers.push(setTimeout(()=>{fill.style.width=`${sim.progress}%`;agent.style.left=`calc(${Math.max(2,Math.min(93,sim.progress))}% - 18px)`;if(sim.progress>=80)ctx.award('target-engineer');const spatial=jugaadSpatialBonus(placements,strategy,scenarioIndex);result.innerHTML=`<div class="jugaad-outcome ${sim.success?'success':'wobble'}"><div class="target-score"><strong>${sim.progress}%</strong><span>${sim.success?'Target reached':'Target not reached'}</span></div><p class="spatial-verdict"><b>Layout:</b> ${esc(spatial.description)} +${spatial.bonus}%</p><div class="score-grid"><div><strong>${flavor.creativity}</strong><span>Creativity</span></div><div><strong>${flavor.practicality}</strong><span>Practicality</span></div><div><strong>${flavor.survival}</strong><span>Chaos rating</span></div></div><p class="reaction">${sim.success?'Your arrangement and tool choices visibly advance the target.':'Repositioning the same tools may work better than changing the text explanation.'}</p><div class="result-actions"><button class="secondary" id="resetBuild">Rebuild</button><button class="secondary" id="room">Friend room</button><button class="primary" id="share">Challenge scenario</button></div></div>`;ctx.record(`Jugaad ${items.join('+')} ${strategy} target ${sim.progress} spatial ${spatial.bonus}`);ctx.ping(sim.success?'pop':'bad');running=false;render();result.querySelector('#resetBuild').onclick=()=>{ctx.replay();result.innerHTML='';simLog.innerHTML='';fill.style.width='0%';agent.style.left='2%';};result.querySelector('#room').onclick=()=>ctx.openRoom({prompt:s.place,answer:`${items.join(' + ')} → target ${sim.progress}%`});result.querySelector('#share').onclick=async()=>ctx.shared(await shareResult({title:meta.title,text:`Can you spatially solve this Jugaad scenario with ${s.items.join(', ')}?`,url:challengeUrl(meta.id,{scenarioIndex})}));},(reduced?20:160+sim.steps.length*230)+120));};
  render();return()=>timers.forEach(clearTimeout);
}
