import {seeded01,clamp} from '../core/random.js';
import {shareResult} from '../core/share.js';
import {orbitConfig} from '../core/play-systems.js';

export const meta={id:'orbit-panic',emoji:'🪐',title:'Orbit Panic',tagline:'Switch lanes, collect energy, spend it on shields, survive the debris.',verb:'Survive',presentation:'Three.js action + Canvas2D fallback'};
const THREE_URL='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.180.0/three.module.min.js';

export function mount(root,ctx){
  let cleanupRenderer=()=>{},alive=true,score=0,started=0,ended=false,lane=1,energy=0,shield=false;
  const reduced=()=>document.documentElement.classList.contains('reduce-motion');
  root.innerHTML=`<section class="game-head"><div><span class="eyebrow">${meta.verb}</span><h1>${meta.emoji} ${meta.title}</h1><p>${meta.tagline}</p></div><span class="engine-pill" id="renderMode">Loading visual engine…</span></section>
  <article class="play-card orbit-card"><div class="visual-toolbar"><span>Survive <strong>30 seconds</strong></span><strong id="timer">0.0s</strong></div><div class="orbit-hud"><div><span>Energy</span><strong id="energy">0 / 3</strong></div><div><span>Shield</span><strong id="shieldState">OFF</strong></div><button type="button" class="power-button" id="shield" disabled>🛡 Spend 3 energy</button></div><div id="orbitStage" class="orbit-stage" aria-label="Orbital survival game"></div>
  <div class="orbit-controls"><button class="secondary" id="inward" aria-label="Move inward">← Inward</button><span id="laneLabel">Middle orbit</span><button class="secondary" id="outward" aria-label="Move outward">Outward →</button></div><div id="feedback" aria-live="polite"></div></article>`;
  const stage=root.querySelector('#orbitStage'),timer=root.querySelector('#timer'),mode=root.querySelector('#renderMode'),laneLabel=root.querySelector('#laneLabel'),feedback=root.querySelector('#feedback'),energyEl=root.querySelector('#energy'),shieldEl=root.querySelector('#shieldState'),shieldButton=root.querySelector('#shield');
  const laneNames=['Inner orbit','Middle orbit','Outer orbit'];
  function refreshHud(){energyEl.textContent=`${energy} / 3`;shieldEl.textContent=shield?'ACTIVE':'OFF';shieldButton.disabled=shield||energy<3||ended;stage.classList.toggle('shielded',shield);}
  function collect(){energy=Math.min(6,energy+1);refreshHud();ctx.ping('pop');stage.classList.remove('energy-flash');void stage.offsetWidth;stage.classList.add('energy-flash');}
  function activateShield(){if(shield||energy<3||ended)return;energy-=3;shield=true;refreshHud();ctx.ping('pop');}
  shieldButton.onclick=activateShield;
  function setLane(next){lane=clamp(next,0,2);laneLabel.textContent=laneNames[lane];ctx.ping('ok');}
  root.querySelector('#inward').onclick=()=>setLane(lane-1);root.querySelector('#outward').onclick=()=>setLane(lane+1);
  const key=e=>{if(e.key==='ArrowLeft'||e.key==='a'||e.key==='A'){e.preventDefault();setLane(lane-1);}if(e.key==='ArrowRight'||e.key==='d'||e.key==='D'){e.preventDefault();setLane(lane+1);}if(e.key===' '){e.preventDefault();activateShield();}};window.addEventListener('keydown',key);
  function collision(h){if(shield){shield=false;h.angle=(h.angle+.7)%(Math.PI*2);refreshHud();stage.classList.remove('shield-burst');void stage.offsetWidth;stage.classList.add('shield-burst');ctx.ping('pop');return false;}return true;}
  function finish(reason='Survived'){if(ended)return;ended=true;score=Math.max(score,Math.min(30,(performance.now()-started)/1000));refreshHud();ctx.record(`Orbit Panic ${score.toFixed(1)}s · ${energy} energy — ${reason}`);ctx.ping(reason==='Survived'?'pop':'bad');feedback.innerHTML=`<div class="finale"><span class="result-kicker">${reason}</span><h2>${score.toFixed(1)}s</h2><p>${reason==='Survived'?`Clean orbit. You banked ${energy} energy.`:'You have joined the debris field.'}</p><div class="result-actions"><button class="primary" id="share">Share run</button><button class="secondary" id="again">Try again</button></div></div>`;feedback.querySelector('#share').onclick=async()=>ctx.shared(await shareResult({title:meta.title,text:`I survived ${score.toFixed(1)}s and banked ${energy} energy in Orbit Panic.`,url:location.href}));feedback.querySelector('#again').onclick=()=>{ctx.replay();cleanupRenderer();feedback.innerHTML='';lane=1;ended=false;score=0;energy=0;shield=false;refreshHud();boot();};}
  async function boot(){started=performance.now();timer.textContent='0.0s';if(reduced()){mode.textContent='Reduced-motion tactical mode';cleanupRenderer=startTactical();return;}mode.textContent='Loading Three.js experiment…';try{const THREE=await Promise.race([import(THREE_URL),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),3500))]);if(!alive)return;mode.textContent=`Three.js 0.180 · ${ctx.quality}`;cleanupRenderer=startThree(THREE);}catch(err){console.warn('Three.js unavailable; using 2D fallback.',err);mode.textContent='2D fallback · Three.js unavailable';cleanupRenderer=startCanvas();}}
  function startThree(THREE){
    let raf=0,last=performance.now();const config=orbitConfig(ctx.dayKey+Date.now(),ctx.quality),haz=config.hazards,shards=config.shards.map(x=>({...x,cooldown:0})),hazObjects=[],shardObjects=[];const scene=new THREE.Scene();scene.background=new THREE.Color(0x0e1117);const camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(0,7.8,8.8);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({antialias:ctx.quality!=='low',powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,ctx.quality==='high'?2:ctx.quality==='low'?1:1.5));stage.replaceChildren(renderer.domElement);renderer.domElement.className='orbit-canvas';scene.add(new THREE.HemisphereLight(0xa7d8ff,0x10131c,2.2));const keyLight=new THREE.DirectionalLight(0xffdfaa,3);keyLight.position.set(4,7,5);scene.add(keyLight);
    const planet=new THREE.Mesh(new THREE.IcosahedronGeometry(1.25,3),new THREE.MeshStandardMaterial({color:0x5576a8,roughness:.8,metalness:.05}));scene.add(planet);const rings=[];for(const r of [2.15,3.05,3.95]){const pts=[];for(let i=0;i<=96;i++){const a=i/96*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r));}const geo=new THREE.BufferGeometry().setFromPoints(pts),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x4b5265,transparent:true,opacity:.7}));scene.add(line);rings.push(line);}const ship=new THREE.Mesh(new THREE.ConeGeometry(.18,.55,5),new THREE.MeshStandardMaterial({color:0xffcc66,emissive:0x4a3310,emissiveIntensity:.8}));ship.rotation.x=Math.PI/2;scene.add(ship);const shieldRing=new THREE.Mesh(new THREE.TorusGeometry(.34,.045,8,32),new THREE.MeshBasicMaterial({color:0x8de0d2,transparent:true,opacity:.8}));shieldRing.rotation.x=Math.PI/2;scene.add(shieldRing);
    for(const h of haz){const m=new THREE.Mesh(new THREE.DodecahedronGeometry(h.size,0),new THREE.MeshStandardMaterial({color:0xff7d91,roughness:.9}));scene.add(m);hazObjects.push(m);}for(const e of shards){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.12,0),new THREE.MeshStandardMaterial({color:0x8de0d2,emissive:0x1c5c54,emissiveIntensity:1.4}));scene.add(m);shardObjects.push(m);}
    function resize(){const r=stage.getBoundingClientRect(),w=Math.max(300,r.width),h=Math.max(260,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}resize();const ro=new ResizeObserver(resize);ro.observe(stage);
    function loop(now){if(!alive||ended)return;const dt=Math.min(.05,(now-last)/1000);last=now;planet.rotation.y+=dt*.22;const radii=[2.15,3.05,3.95],pa=-Math.PI/2;ship.position.set(Math.cos(pa)*radii[lane],.08,Math.sin(pa)*radii[lane]);ship.rotation.z=-pa;shieldRing.position.copy(ship.position);shieldRing.visible=shield;shieldRing.rotation.z+=dt*2;
      for(let i=0;i<haz.length;i++){const h=haz[i];h.angle=(h.angle+h.speed*dt)%(Math.PI*2);hazObjects[i].position.set(Math.cos(h.angle)*radii[h.lane],0,Math.sin(h.angle)*radii[h.lane]);hazObjects[i].rotation.x+=dt;hazObjects[i].rotation.y+=dt*.8;const d=Math.abs(((h.angle-pa+Math.PI*3)%(Math.PI*2))-Math.PI);if(h.lane===lane&&d<.09&&collision(h)){score=(now-started)/1000;finish('Collision');return;}}
      for(let i=0;i<shards.length;i++){const e=shards[i];const o=shardObjects[i];if(!e.active){e.cooldown-=dt;o.visible=false;if(e.cooldown<=0){e.active=true;e.angle=(e.angle+Math.PI*.73)%(Math.PI*2);o.visible=true;}continue;}e.angle=(e.angle+e.speed*dt)%(Math.PI*2);o.position.set(Math.cos(e.angle)*radii[e.lane],.04,Math.sin(e.angle)*radii[e.lane]);o.rotation.y+=dt*2.4;const d=Math.abs(((e.angle-pa+Math.PI*3)%(Math.PI*2))-Math.PI);if(e.lane===lane&&d<.1){e.active=false;e.cooldown=3.5;collect();}}
      score=(now-started)/1000;timer.textContent=`${score.toFixed(1)}s`;if(score>=30){finish('Survived');return;}renderer.render(scene,camera);raf=requestAnimationFrame(loop);}raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);ro.disconnect();[...hazObjects,...shardObjects,planet,ship,shieldRing].forEach(o=>{o.geometry?.dispose();o.material?.dispose();});rings.forEach(r=>{r.geometry.dispose();r.material.dispose();});renderer.dispose();renderer.domElement.remove();};
  }
  function startCanvas(){let raf=0,last=performance.now();const config=orbitConfig(ctx.dayKey+Date.now(),ctx.quality),haz=config.hazards,shards=config.shards.map(x=>({...x,cooldown:0})),canvas=document.createElement('canvas');canvas.className='orbit-canvas';stage.replaceChildren(canvas);const c=canvas.getContext('2d');function loop(now){if(!alive||ended)return;const r=stage.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,ctx.quality==='high'?2:1.35),w=Math.max(300,Math.round(r.width*dpr)),h=Math.max(260,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const dt=Math.min(.05,(now-last)/1000);last=now;c.fillStyle='#0e1117';c.fillRect(0,0,w,h);const cx=w/2,cy=h/2,rs=[Math.min(w,h)*.22,Math.min(w,h)*.31,Math.min(w,h)*.40];c.strokeStyle='#41485b';c.lineWidth=2*dpr;for(const rr of rs){c.beginPath();c.arc(cx,cy,rr,0,Math.PI*2);c.stroke();}c.fillStyle='#5576a8';c.beginPath();c.arc(cx,cy,Math.min(w,h)*.13,0,Math.PI*2);c.fill();const pa=-Math.PI/2,px=cx+Math.cos(pa)*rs[lane],py=cy+Math.sin(pa)*rs[lane];c.fillStyle='#ffcc66';c.beginPath();c.arc(px,py,9*dpr,0,Math.PI*2);c.fill();if(shield){c.strokeStyle='#8de0d2';c.lineWidth=4*dpr;c.beginPath();c.arc(px,py,17*dpr,0,Math.PI*2);c.stroke();}
      for(const h1 of haz){h1.angle=(h1.angle+h1.speed*dt)%(Math.PI*2);const x=cx+Math.cos(h1.angle)*rs[h1.lane],y=cy+Math.sin(h1.angle)*rs[h1.lane];c.fillStyle='#ff7d91';c.beginPath();c.arc(x,y,8*dpr,0,Math.PI*2);c.fill();const d=Math.abs(((h1.angle-pa+Math.PI*3)%(Math.PI*2))-Math.PI);if(h1.lane===lane&&d<.1&&collision(h1)){score=(now-started)/1000;finish('Collision');return;}}
      for(const e of shards){if(!e.active){e.cooldown-=dt;if(e.cooldown<=0){e.active=true;e.angle=(e.angle+Math.PI*.73)%(Math.PI*2);}continue;}e.angle=(e.angle+e.speed*dt)%(Math.PI*2);const x=cx+Math.cos(e.angle)*rs[e.lane],y=cy+Math.sin(e.angle)*rs[e.lane];c.fillStyle='#8de0d2';c.save();c.translate(x,y);c.rotate(now/500);c.fillRect(-6*dpr,-6*dpr,12*dpr,12*dpr);c.restore();const d=Math.abs(((e.angle-pa+Math.PI*3)%(Math.PI*2))-Math.PI);if(e.lane===lane&&d<.11){e.active=false;e.cooldown=3.5;collect();}}
      score=(now-started)/1000;timer.textContent=`${score.toFixed(1)}s`;if(score>=30){finish('Survived');return;}raf=requestAnimationFrame(loop);}raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);canvas.remove();};}
  function startTactical(){let step=0,dead=false;const board=document.createElement('div');board.className='tactical-orbit';stage.replaceChildren(board);function drawStep(){if(dead||ended)return;if(step>=12){score=30;finish('Survived');return;}const blocked=Math.floor(seeded01(`${ctx.dayKey}|tactical|${step}`)*3)%3,shardLane=(blocked+1+Math.floor(seeded01(`${ctx.dayKey}|shard|${step}`)*2))%3;board.innerHTML=`<p>Turn ${step+1}/12</p><div class="tactical-lanes">${laneNames.map((n,i)=>`<button data-lane="${i}" class="${i===blocked?'danger-lane':''}"><span>${i===blocked?'☄️':i===shardLane?'✦':'○'}</span>${n}</button>`).join('')}</div><small>Hazards are shown in reduced-motion mode. ✦ earns one energy.</small>`;board.querySelectorAll('button').forEach(b=>b.onclick=()=>{lane=Number(b.dataset.lane);laneLabel.textContent=laneNames[lane];if(lane===blocked){if(shield){shield=false;refreshHud();step++;timer.textContent=`${(step*2.5).toFixed(1)}s`;ctx.ping('pop');drawStep();}else{score=step*2.5;dead=true;finish('Collision');}}else{if(lane===shardLane)collect();step++;timer.textContent=`${(step*2.5).toFixed(1)}s`;drawStep();}});}drawStep();return()=>board.remove();}
  const onSettings=e=>{ctx.quality=e.detail?.quality||ctx.quality;if(ended)return;cleanupRenderer();boot();};window.addEventListener('funlab:settings',onSettings);refreshHud();boot();
  return()=>{alive=false;cleanupRenderer();window.removeEventListener('keydown',key);window.removeEventListener('funlab:settings',onSettings);};
}
