import {pick} from '../core/random.js';
import {challengeUrl,shareResult} from '../core/share.js';
import {adventureHotspots,adventureSceneSpec,adventureLoot,adventureItemEffect} from '../core/play-systems.js';
export const meta={id:'what-next',emoji:'🌀',title:'What Happens Next?',tagline:'Explore scene-specific maps, watch the world move, and carry odd objects into later scenes.',verb:'Explore',presentation:'Spatial 2D adventure maps + moving world actors + persistent inventory'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const STARTS=[{text:'A monkey steals your phone at a railway platform.',theme:'station',icon:'🐒'},{text:'Your lift opens onto a floor that does not exist.',theme:'lift',icon:'🚪'},{text:'A courier delivers a box addressed to “The Future You”.',theme:'parcel',icon:'📦'},{text:'Your fridge sends you a notification: “We need to talk.”',theme:'kitchen',icon:'🧊'}];
const OUTCOMES={0:['You inspect the clue and find something useful hidden in plain sight.','Logic works briefly. Everyone nearby looks disappointed.'],1:['You take the risky route. It works, but creates a much stranger problem.','Nothing goes to plan; somehow this opens the next path.'],2:['You recruit a stranger. They are far too enthusiastic about this.','Someone helps, but now they also want an explanation.']};
export function mount(root,ctx,challenge){
  const incoming=String(challenge?.start||'').slice(0,240),start=STARTS.find(x=>x.text===incoming)||pick(STARTS,ctx.dayKey);let turn=0,player={x:3,y:4},story=[start.text],spots=[],inventory=[],equipped=null,scene=null,actorStep=0,actorTimer=0,transitioning=false;const cap=ctx.hasUnlock('expedition-pack')?4:3;
  root.innerHTML=`<section class="game-head"><div><span class="eyebrow">${meta.verb}</span><h1>${meta.emoji} ${meta.title}</h1><p>${meta.tagline}</p></div><span class="engine-pill">2D exploration · pack ${cap}</span></section><article class="play-card adventure-card"><div class="adventure-top"><div><span class="result-kicker">Current problem</span><h2>${esc(start.text)}</h2></div><span id="turnLabel">Scene 1/4</span></div><div class="adventure-pack"><span class="result-kicker">Carry pack</span><div id="pack"><small>Nothing yet. Explore a clue.</small></div></div><div class="adventure-map ${start.theme}" id="map" tabindex="0" aria-label="Explore the scene with arrow keys or direction controls"><div class="scene-layer" id="sceneLayer" aria-hidden="true"></div><div class="player-token" id="player">🙂</div></div><div class="adventure-hint" id="hint">Move onto one of the glowing scene clues.</div><div class="dpad"><span></span><button type="button" data-move="0,-1">↑</button><span></span><button type="button" data-move="-1,0">←</button><button type="button" data-move="0,1">↓</button><button type="button" data-move="1,0">→</button></div><div id="storyResult" aria-live="polite"></div></article>`;
  const map=root.querySelector('#map'),playerEl=root.querySelector('#player'),hint=root.querySelector('#hint'),result=root.querySelector('#storyResult'),pack=root.querySelector('#pack'),layer=root.querySelector('#sceneLayer');
  function renderPack(){pack.innerHTML=inventory.length?inventory.map(x=>`<button type="button" class="pack-item ${equipped===x?'selected':''}" data-pack="${esc(x)}">🎒 ${esc(x)}</button>`).join(''):'<small>Nothing yet. Explore a clue.</small>';pack.querySelectorAll('[data-pack]').forEach(b=>b.onclick=()=>{equipped=equipped===b.dataset.pack?null:b.dataset.pack;renderPack();hint.textContent=equipped?`${equipped} equipped. Walk onto a clue to use it.`:'Item returned to pack.';ctx.ping('ok');});}
  function stopActor(){clearInterval(actorTimer);actorTimer=0;}
  function renderScene(){scene=adventureSceneSpec(start.theme,turn,ctx.dayKey);map.dataset.terrain=scene.terrain;layer.innerHTML=scene.objects.map(o=>`<span class="scene-object ${o.kind}" style="--x:${o.x};--y:${o.y}" title="${esc(o.label)}">${o.icon}</span>`).join('')+`<span class="scene-actor" id="sceneActor" title="${esc(scene.actor.label)}">${scene.actor.icon}</span>`;actorStep=0;positionActor();stopActor();if(!document.documentElement.classList.contains('reduce-motion'))actorTimer=setInterval(()=>{actorStep=(actorStep+1)%scene.actor.path.length;positionActor();},900);}
  function positionActor(){const a=layer.querySelector('#sceneActor');if(!a||!scene)return;const [x,y]=scene.actor.path[actorStep%scene.actor.path.length];a.style.setProperty('--x',x);a.style.setProperty('--y',y);}
  function resetScene(){player={x:3,y:4};spots=adventureHotspots(start.theme,ctx.dayKey,turn);renderScene();draw();}
  function draw(){playerEl.style.setProperty('--x',player.x);playerEl.style.setProperty('--y',player.y);map.querySelectorAll('.hotspot').forEach(x=>x.remove());for(const s of spots){const b=document.createElement('button');b.type='button';b.className='hotspot';b.style.setProperty('--x',s.x);b.style.setProperty('--y',s.y);b.dataset.id=s.id;b.innerHTML=`<span>${s.icon}</span><small>${esc(s.label)}</small>`;b.onclick=()=>{if(transitioning)return;player={x:s.x,y:s.y};draw();resolve(s);};map.append(b);}root.querySelector('#turnLabel').textContent=`Scene ${Math.min(turn+1,4)}/4`;
  }
  function blocked(x,y){return scene?.objects?.some(o=>o.kind==='obstacle'&&o.x===x&&o.y===y);}
  function inspectCell(){const o=scene?.objects?.find(o=>o.kind==='object'&&o.x===player.x&&o.y===player.y);if(o){hint.textContent=`You inspect the ${o.label}. It changes how the scene reads, but does not consume a scene choice.`;ctx.ping('ok');}const ap=scene?.actor?.path?.[actorStep];if(ap&&ap[0]===player.x&&ap[1]===player.y){hint.textContent=`The ${scene.actor.label} notices you and moves on. The world is not waiting politely.`;ctx.ping('pop');}}
  function move(dx,dy){if(transitioning)return;const nx=Math.max(1,Math.min(6,player.x+dx)),ny=Math.max(1,Math.min(4,player.y+dy));if(blocked(nx,ny)){const o=scene.objects.find(o=>o.kind==='obstacle'&&o.x===nx&&o.y===ny);hint.textContent=`The ${o.label} blocks that route. Go around it.`;ctx.ping('bad');return;}player={x:nx,y:ny};draw();inspectCell();const hit=spots.find(s=>s.x===player.x&&s.y===player.y);if(hit)resolve(hit);else ctx.ping('ok');}
  function resolve(s){if(turn>=4||transitioning)return;transitioning=true;let outcome=pick(OUTCOMES[s.id],`${ctx.dayKey}|${turn}|${s.id}|${story.join('')}`),used=null;if(equipped){used=equipped;const effect=adventureItemEffect(equipped,s.id,turn);outcome+=` ${effect.text}`;inventory=inventory.filter(x=>x!==equipped);equipped=null;if(turn>0)ctx.award('carry-on');}const loot=adventureLoot(start.theme,turn,`${ctx.dayKey}|${s.id}`);const packed=inventory.length<cap&&!inventory.includes(loot);if(packed)inventory.push(loot);story.push(`${s.label}: ${outcome}`);turn++;renderPack();ctx.ping('pop');result.innerHTML=`<p class="reaction"><strong>${s.icon} ${esc(s.label)}</strong> — ${esc(outcome)}</p><p class="loot-line">${used?`Used ${esc(used)} · `:''}Found <b>${esc(loot)}</b>${packed?' and packed it.':' but the pack could not take it.'}</p>`;hint.textContent=outcome;if(turn>=4){finish();return;}spots=[];draw();setTimeout(()=>{transitioning=false;resetScene();},document.documentElement.classList.contains('reduce-motion')?0:320);}
  function finish(){stopActor();spots=[];draw();transitioning=false;result.innerHTML=`<div class="finale"><span class="result-kicker">You escaped the scene</span><h2>Mostly.</h2><p>${esc(story.at(-1))}</p><p>Pack at exit: ${inventory.length?inventory.map(esc).join(', '):'empty'}</p><div class="result-actions"><button class="secondary" id="again">New route</button><button class="primary" id="share">Share starting chaos</button></div></div>`;ctx.record(`${story.at(-1)} · pack ${inventory.join('|')}`);ctx.ping('pop');result.querySelector('#again').onclick=()=>{ctx.replay();turn=0;story=[start.text];inventory=[];equipped=null;result.innerHTML='';hint.textContent='Move onto one of the glowing scene clues.';renderPack();resetScene();};result.querySelector('#share').onclick=async()=>ctx.shared(await shareResult({title:meta.title,text:`Explore this absurd starting situation: ${start.text}`,url:challengeUrl(meta.id,{start:start.text})}));}
  root.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [dx,dy]=b.dataset.move.split(',').map(Number);move(dx,dy);});const key=e=>{const mapKey={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]};const m=mapKey[e.key];if(m&&!['INPUT','TEXTAREA'].includes(e.target?.tagName)){e.preventDefault();move(...m);}};map.addEventListener('keydown',key);renderPack();resetScene();return()=>{map.removeEventListener('keydown',key);stopActor();};
}
