import {runIntelligence,endpointLabel} from '../core/ai-adapter.js';
import {challengeUrl,shareResult} from '../core/share.js';
import {visualIdentity,battlePlan,arenaChoices,arenaEnvironment,BATTLE_ACTIONS,battleActionAvailability,resolveBattleAction,tickBattleCooldowns} from '../core/play-systems.js';

export const meta={id:'who-wins',emoji:'⚔️',title:'Who Would Win?',tagline:'Read the next exchange, time a counter, and change the fight.',verb:'Battle',presentation:'Telegraphed 2D arena combat with cooldown tactics'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

export function mount(root,ctx,challenge){
  let timers=[],alive=true,backed='a',stance='balanced',currentHp={a:100,b:100},cooldowns={guard:0,power:0,trick:0},pendingAction=null,exchangeIndex=0,plan=null,base=null,battleNames={a:'A',b:'B'},running=false;
  const A0=String(challenge?.a||'Elephant').slice(0,60),B0=String(challenge?.b||'Tractor').slice(0,60);
  let arena=arenaEnvironment(ctx.dayKey,A0,B0,ctx.unlocks());
  root.innerHTML=`<section class="game-head"><div><span class="eyebrow">${meta.verb}</span><h1>${meta.emoji} ${meta.title}</h1><p>${meta.tagline}</p></div><span class="engine-pill">${endpointLabel()} + local combat</span></section>
  <article class="play-card battle-card"><form id="setup" class="battle-setup"><label>Contender A<input name="a" maxlength="60" value="${esc(A0)}" required></label><span class="vs">VS</span><label>Contender B<input name="b" maxlength="60" value="${esc(B0)}" required></label></form>
  <div class="arena-picker"><span class="result-kicker">Arena</span><div id="arenaSelect"></div></div>
  <div class="battle-arena env-${arena.id}" id="arena"><div class="arena-sky"><i></i><i></i><i></i></div><div class="arena-crowd">• • • • • • • • • •</div><div class="arena-floor"></div>
  <button type="button" class="fighter fighter-a selected" id="fighterA"><span class="fighter-orb" id="orbA"></span><b id="nameA">${esc(A0)}</b><div class="hp"><span id="hpA"></span></div></button><div class="arena-vs">VS</div><button type="button" class="fighter fighter-b" id="fighterB"><span class="fighter-orb" id="orbB"></span><b id="nameB">${esc(B0)}</b><div class="hp"><span id="hpB"></span></div></button><div class="arena-fx" id="fx"></div></div>
  <section class="tactic-panel"><div><span class="result-kicker">Opening stance</span><p>Back a fighter and bias the opening exchanges. During battle, react to each telegraph.</p></div><div class="tactic-row" id="stances"><button type="button" data-stance="power">💥 Power</button><button type="button" data-stance="guard">🛡 Guard</button><button type="button" data-stance="trick">🌀 Trick</button><button type="button" class="selected" data-stance="balanced">⚖ Balanced</button></div><button class="primary" type="button" id="fight">Start battle</button></section>
  <section class="combat-console" id="console" hidden><div class="telegraph" id="telegraph"><span class="result-kicker">Next exchange</span><strong>Waiting…</strong><small>Choose a timed action before the exchange resolves.</small><div class="telegraph-timer"><span id="telegraphBar"></span></div></div><div class="combat-actions" id="combatActions"></div><button type="button" class="secondary" id="resolveExchange" hidden>Resolve exchange</button></section>
  <div id="result" aria-live="polite"></div></article>`;
  const form=root.querySelector('#setup'),arenaEl=root.querySelector('#arena'),hpA=root.querySelector('#hpA'),hpB=root.querySelector('#hpB'),fx=root.querySelector('#fx'),fight=root.querySelector('#fight'),fighterA=root.querySelector('#fighterA'),fighterB=root.querySelector('#fighterB'),consoleEl=root.querySelector('#console'),telegraph=root.querySelector('#telegraph'),bar=root.querySelector('#telegraphBar'),actions=root.querySelector('#combatActions'),resolveButton=root.querySelector('#resolveExchange');
  hpA.style.width=hpB.style.width='100%';
  function arenaMarkup(){const choices=arenaChoices(ctx.unlocks());root.querySelector('#arenaSelect').innerHTML=choices.map(x=>`<button type="button" data-arena="${x.id}" class="${x.id===arena.id?'selected':''}">${x.icon} ${x.label}</button>`).join('');root.querySelectorAll('[data-arena]').forEach(b=>b.onclick=()=>{if(running)return;arena=choices.find(x=>x.id===b.dataset.arena)||arena;arenaMarkup();applyArena();ctx.ping('ok');});}
  function applyArena(){arenaEl.classList.remove('env-rooftop','env-scrapyard','env-storm');arenaEl.classList.add(`env-${arena.id}`);arenaEl.dataset.arena=arena.label;}
  function paint(){const a=form.elements.a.value.trim()||'A',b=form.elements.b.value.trim()||'B',va=visualIdentity(a),vb=visualIdentity(b);root.querySelector('#nameA').textContent=a;root.querySelector('#nameB').textContent=b;root.querySelector('#orbA').style.cssText=`--h:${va.hue};--h2:${va.hue2}`;root.querySelector('#orbA').textContent=va.glyph;root.querySelector('#orbB').style.cssText=`--h:${vb.hue};--h2:${vb.hue2}`;root.querySelector('#orbB').textContent=vb.glyph;}
  form.addEventListener('input',paint);paint();arenaMarkup();applyArena();
  function selectSide(side){if(running)return;backed=side;fighterA.classList.toggle('selected',side==='a');fighterB.classList.toggle('selected',side==='b');ctx.ping('ok');}
  fighterA.onclick=()=>selectSide('a');fighterB.onclick=()=>selectSide('b');
  root.querySelectorAll('[data-stance]').forEach(b=>b.onclick=()=>{if(running)return;stance=b.dataset.stance;root.querySelectorAll('[data-stance]').forEach(x=>x.classList.toggle('selected',x===b));ctx.ping('ok');});
  function clearTimers(){timers.forEach(clearTimeout);timers=[];}
  function actionMarkup(ev){const available=battleActionAvailability(ev,backed,cooldowns);actions.innerHTML=Object.entries(BATTLE_ACTIONS).map(([id,a])=>{const cd=cooldowns[id]||0,ok=available[id];return `<button type="button" data-action="${id}" class="combat-action ${pendingAction===id?'selected':''}" ${ok&&!pendingAction?'':'disabled'}><span>${a.icon}</span><b>${a.label}</b><small>${cd?`cooldown ${cd}`:(ok?'ready':'not useful now')}</small></button>`;}).join('');actions.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(pendingAction)return;pendingAction=b.dataset.action;actionMarkup(ev);ctx.ping('pop');});}
  function setTelegraph(ev){const attacker=ev.attacker==='a'?battleNames.a:battleNames.b,defender=ev.defender==='a'?battleNames.a:battleNames.b;telegraph.querySelector('strong').textContent=`${attacker} → ${defender} · incoming ${ev.damage}`;telegraph.querySelector('small').textContent=ev.defender===backed?'Your fighter is under pressure. Guard or counter may help.':ev.attacker===backed?'Your fighter has initiative. Power or counter may help.':'Watch the exchange; your fighter is not directly involved.';pendingAction=null;actionMarkup(ev);bar.style.width='100%';}
  function animateDamage(ev,res){const attacker=ev.attacker==='a'?fighterA:fighterB,defender=ev.defender==='a'?fighterA:fighterB;currentHp[ev.defender]=Math.max(0,currentHp[ev.defender]-res.damage);if(res.counterDamage)currentHp[ev.attacker]=Math.max(0,currentHp[ev.attacker]-res.counterDamage);hpA.style.width=`${currentHp.a}%`;hpB.style.width=`${currentHp.b}%`;attacker.classList.remove('strike');defender.classList.remove('hit');void attacker.offsetWidth;attacker.classList.add('strike');defender.classList.add('hit');fx.textContent=res.used?`${BATTLE_ACTIONS[res.used].icon} ${res.label}`:`−${res.damage}`;fx.classList.remove('pop');void fx.offsetWidth;fx.classList.add('pop');ctx.ping(res.used?'pop':'ok');}
  function resolveCurrent(ev){if(!alive||!running)return;const res=resolveBattleAction(ev,pendingAction,backed,cooldowns);cooldowns=tickBattleCooldowns(res.cooldowns);animateDamage(ev,res);exchangeIndex++;if(currentHp.a<=0||currentHp.b<=0||exchangeIndex>=plan.events.length){finishBattle();return;}timers.push(setTimeout(()=>queueExchange(),document.documentElement.classList.contains('reduce-motion')?0:260));}
  function queueExchange(){if(!alive||!running)return;const ev=plan.events[exchangeIndex];setTelegraph(ev);const reduced=document.documentElement.classList.contains('reduce-motion');resolveButton.hidden=!reduced;if(reduced){resolveButton.disabled=false;resolveButton.onclick=()=>{resolveButton.disabled=true;resolveCurrent(ev);};bar.style.width='100%';return;}bar.style.transition='none';bar.style.width='100%';requestAnimationFrame(()=>{bar.style.transition='width .72s linear';bar.style.width='0%';});timers.push(setTimeout(()=>resolveCurrent(ev),760));}
  fight.onclick=async()=>{if(running)return;clearTimers();const a=form.elements.a.value.trim(),b=form.elements.b.value.trim();if(!a||!b)return;running=true;fight.disabled=true;fighterA.classList.remove('winner');fighterB.classList.remove('winner');currentHp={a:100,b:100};cooldowns={guard:0,power:0,trick:0};exchangeIndex=0;hpA.style.width=hpB.style.width='100%';root.querySelector('#result').innerHTML='<p class="thinking">Arena calibration…</p>';base=await runIntelligence('versus',{a,b});if(!alive)return;battleNames={a,b};plan=battlePlan({a,b,aProbability:base.aProbability,backed,tactic:stance,seed:`${ctx.dayKey}|${arena.id}`});root.querySelector('#result').innerHTML=`<div class="arena-status"><span>${arena.icon} ${arena.label}</span><span>Base odds: A ${base.aProbability}%</span><span>Opening stance: A ${plan.adjusted}%</span></div>`;consoleEl.hidden=false;queueExchange();};
  function finishBattle(){if(!alive)return;running=false;clearTimers();consoleEl.hidden=true;const a=battleNames.a,b=battleNames.b;let winnerSide=currentHp.a===currentHp.b?plan.winner:(currentHp.a>currentHp.b?'a':'b');if(currentHp.a<=0)winnerSide='b';if(currentHp.b<=0)winnerSide='a';const winner=winnerSide==='a'?a:b,loser=winnerSide==='a'?b:a;const flipped=winner!==base.winner;if(flipped){ctx.award('tactical-upset');arenaMarkup();}fighterA.classList.toggle('winner',winnerSide==='a');fighterB.classList.toggle('winner',winnerSide==='b');const out=root.querySelector('#result');out.innerHTML=`<article class="result-card battle-result"><span class="result-kicker">Arena winner</span><h2>${esc(winner)}</h2><p>${esc(base.reason)} ${flipped?'Your live timing and opening stance overturned the base prediction.':'The base prediction survived your live interventions.'}</p><p class="combat-score">Final health · ${esc(a)} ${currentHp.a} · ${esc(b)} ${currentHp.b}</p><div class="result-actions"><button class="secondary" id="again">Rematch</button><button class="secondary" id="room">Friend room</button><button class="primary" id="share">Challenge a friend</button></div><small>${esc(loser)} may request a slower telegraph.</small></article>`;ctx.record(`${a} vs ${b}: ${winner} (${stance}, ${arena.id}, hp ${currentHp.a}-${currentHp.b})`);ctx.ping('pop');fight.disabled=false;out.querySelector('#again').onclick=()=>{ctx.replay();form.elements.a.value=b;form.elements.b.value=a;selectSide(backed==='a'?'b':'a');paint();fight.click();};out.querySelector('#room').onclick=()=>ctx.openRoom({prompt:`${a} vs ${b}`,answer:`${winner} via ${stance} in ${arena.label}`});out.querySelector('#share').onclick=async()=>ctx.shared(await shareResult({title:meta.title,text:`I backed ${backed==='a'?a:b} in ${a} vs ${b}. Can your timing beat mine?`,url:challengeUrl(meta.id,{a,b})}));}
  return()=>{alive=false;running=false;clearTimers();};
}
